import type { ContentItem } from '@/lib/types';

export const communityContent: ContentItem[] = [
  {
    id: 'comm-1',
    titleEn: 'Starting a Small Business — Step by Step',
    titleTa: 'சிறு வணிகத்தைத் தொடங்குதல் — படிப்படியாக',
    bodyEn: 'Start with what you know. Ask yourself: what do people in my community need? Can I provide it? Begin by testing your idea with a few customers. Keep your costs low at first. Track every rupee coming in and going out. Register as a sole trader when you are ready to grow.',
    bodyTa: 'நீங்கள் அறிந்ததிலிருந்து தொடங்குங்கள். உங்களை நீங்களே கேளுங்கள்: என் சமூகத்தில் மக்களுக்கு என்ன தேவை? நான் அதை வழங்க முடியுமா? சில வாடிக்கையாளர்களுடன் உங்கள் யோசனையை சோதிப்பதன் மூலம் தொடங்குங்கள். முதலில் உங்கள் செலவுகளை குறைவாக வையுங்கள்.',
    tags: ['business', 'startup', 'guide'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'comm-2',
    titleEn: 'Understanding Income vs Profit',
    titleTa: 'வருமானம் vs லாபம் புரிந்துகொள்ளுதல்',
    bodyEn: 'Income is the total money you receive. Profit is what remains after you subtract your costs. If you sell 100 palmyra sweets at LKR 50 each, your income is LKR 5,000. If ingredients, transport, and packaging cost LKR 3,000, your profit is LKR 2,000. Always know your profit, not just your income.',
    bodyTa: 'வருமானம் என்பது நீங்கள் பெறும் மொத்த பணம். லாபம் என்பது உங்கள் செலவுகளை கழித்த பின் மீதமுள்ளது. நீங்கள் 100 பனம் இனிப்புகளை ஒன்றுக்கு 50 ரூபாய் வீதம் விற்றால், உங்கள் வருமானம் 5,000 ரூபாய். பொருட்கள், போக்குவரத்து, பேக்கேஜிங் 3,000 ரூபாய் என்றால், உங்கள் லாபம் 2,000 ரூபாய்.',
    tags: ['finance', 'bookkeeping', 'basics'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'comm-3',
    titleEn: 'Samurdhi and Microfinance Options',
    titleTa: 'சமுர்தி மற்றும் நுண்நிதி விருப்பங்கள்',
    bodyEn: 'The Samurdhi programme provides livelihood support, savings schemes, and small loans for low-income families. Contact your local Samurdhi bank or Grama Niladhari office. Cooperative societies also offer savings and loan facilities to members. Compare interest rates before borrowing.',
    bodyTa: 'சமுர்தி திட்டம் குறைந்த வருமான குடும்பங்களுக்கு வாழ்வாதார ஆதரவு, சேமிப்பு திட்டங்கள் மற்றும் சிறிய கடன்களை வழங்குகிறது. உங்கள் உள்ளூர் சமுர்தி வங்கி அல்லது கிராம நிலதாரி அலுவலகத்தை தொடர்பு கொள்ளுங்கள்.',
    tags: ['finance', 'loans', 'Samurdhi'],
    region: 'all',
    type: 'resource',
  },
  {
    id: 'comm-4',
    titleEn: 'Priyanka — Tailoring Business, Kilinochchi',
    titleTa: 'பிரியங்கா — தையல் வணிகம், கிளிநொச்சி',
    bodyEn: 'Priyanka started with a single sewing machine gifted by a local NGO after the war. She began tailoring school uniforms for neighbours. Today she employs two assistants and sells via WhatsApp. Her advice: "Start with what people need today, not with a big dream. The dream comes later."',
    bodyTa: 'பிரியங்கா போருக்குப் பின் ஒரு உள்ளூர் NGO வழங்கிய ஒரு தையல் இயந்திரத்துடன் தொடங்கினார். அண்டை வீட்டாருக்கு பள்ளி சீருடைகளை தைக்கத் தொடங்கினார். இன்று இரண்டு உதவியாளர்களை வேலைக்கு வைத்து WhatsApp மூலம் விற்கிறார்.',
    tags: ['story', 'tailoring', 'women', 'Kilinochchi'],
    region: 'north',
    type: 'story',
  },
  {
    id: 'comm-5',
    titleEn: 'Rajan — Fishing Cooperative, Mullaitivu',
    titleTa: 'ராஜன் — மீன்பிடி கூட்டுறவு, முல்லைத்தீவு',
    bodyEn: 'Rajan helped form a fishing cooperative with 12 families in Mullaitivu. They pooled resources to buy a boat and now share catches and costs equally. The cooperative also negotiates better prices with buyers. His advice: "Alone we struggled. Together we survive."',
    bodyTa: 'ராஜன் முல்லைத்தீவில் 12 குடும்பங்களுடன் மீன்பிடி கூட்டுறவை உருவாக்க உதவினார். அவர்கள் படகு வாங்க வளங்களை ஒன்றிணைத்து இப்போது மீன்களையும் செலவுகளையும் சமமாக பகிர்ந்து கொள்கிறார்கள்.',
    tags: ['story', 'fishing', 'cooperative', 'Mullaitivu'],
    region: 'north',
    type: 'story',
  },
];
