import type { ContentItem } from '@/lib/types';

export const communityContent: ContentItem[] = [
  // === UNDERSTANDING COMMUNITY ECONOMY ===
  {
    id: 'comm-economy',
    titleEn: 'The Tamil Community Economy — Strength in Resourcefulness',
    titleTa: 'தமிழ் சமூக பொருளாதாரம் — வளமிக்கத்தில் வலிமை',
    bodyEn: 'The Tamil areas of Sri Lanka have a vibrant informal economy driven by decades of resilience. Women-led microenterprises — tailoring, food production, small shops — form the backbone of many households. Agricultural cooperatives connect farmers to markets. Fishing communities pool resources for boats and share catches. The palmyra industry, handloom weaving, and traditional crafts provide income and preserve cultural identity. Increasingly, digital tools are creating new opportunities: WhatsApp groups connecting producers to buyers, social media marketing for local goods, and mobile payments making transactions easier. The challenge is connecting local production to wider markets while keeping the economic benefits within the community.',
    bodyTa: 'இலங்கையின் தமிழ் பகுதிகளில் பல தசாப்த கால நெகிழ்திறனால் இயக்கப்படும் துடிப்பான முறைசாரா பொருளாதாரம் உள்ளது. பெண்கள் தலைமையிலான நுண் நிறுவனங்கள் — தையல், உணவு உற்பத்தி, சிறு கடைகள் — பல வீடுகளின் முதுகெலும்பாக உள்ளன. வேளாண் கூட்டுறவு சங்கங்கள் விவசாயிகளை சந்தைகளுடன் இணைக்கின்றன. டிஜிட்டல் கருவிகள் புதிய வாய்ப்புகளை உருவாக்குகின்றன.',
    tags: ['economy', 'informal sector', 'women', 'agriculture', 'fishing', 'overview'],
    region: 'all',
    type: 'explainer',
  },

  // === STARTING A MICRO-ENTERPRISE ===
  {
    id: 'comm-startup-guide',
    titleEn: 'Starting a Micro-Enterprise — A Complete Guide',
    titleTa: 'நுண் நிறுவனத்தைத் தொடங்குதல் — முழுமையான வழிகாட்டி',
    bodyEn: 'Step 1: Find your idea. Ask: what do people in my area need? What am I good at? What can I start with very little money? Step 2: Test it small. Before investing, sell to a few people first. Get feedback. Step 3: Know your costs. List everything you need to spend — materials, transport, packaging, phone credit. Step 4: Set your price. Your price must cover costs + your time + some profit. Do not underprice yourself. Step 5: Start selling. Use WhatsApp, your local market, word of mouth. Step 6: Track your money. Write down every rupee in and every rupee out from day one. Use a notebook or Google Sheets. Step 7: Grow slowly. Reinvest some profit to improve quality or expand. Do not take loans until you have proven the business works. Step 8: Register when ready. Once earning regularly, register as a sole trader at your Divisional Secretariat (cost: approximately LKR 1,000).',
    bodyTa: 'படி 1: உங்கள் யோசனையை கண்டறியுங்கள். கேளுங்கள்: என் பகுதியில் மக்களுக்கு என்ன தேவை? நான் எதில் நிபுணர்? மிகக் குறைந்த பணத்தில் என்ன தொடங்க முடியும்? படி 2: சிறிதாக சோதியுங்கள். முதலீடு செய்வதற்கு முன், சிலருக்கு விற்கவும். கருத்து பெறுங்கள். படி 3: உங்கள் செலவுகளை அறியுங்கள். படி 4: விலை நிர்ணயிக்கவும் — செலவுகள் + உங்கள் நேரம் + லாபம். படி 5: விற்க தொடங்குங்கள். படி 6: பணத்தை கண்காணியுங்கள். படி 7: மெதுவாக வளருங்கள். படி 8: தயாராகும்போது பதிவு செய்யுங்கள்.',
    tags: ['business', 'startup', 'guide', 'step-by-step', 'micro-enterprise'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'comm-registration',
    titleEn: 'Registering a Business in Sri Lanka',
    titleTa: 'இலங்கையில் வணிகத்தை பதிவு செய்தல்',
    bodyEn: 'For a micro-enterprise, the simplest option is registering as a sole proprietor. Where: your nearest Divisional Secretariat office. What you need: National Identity Card, proof of address, a chosen business name. Cost: approximately LKR 500–1,000. Timeline: usually processed within a few days. Benefits of registering: you can open a business bank account, apply for small loans, issue receipts, and it protects your business name. You do not need to register until you are earning regularly — there is no legal requirement to register a very small business, but it becomes important as you grow. For larger businesses or partnerships, consult the Registrar of Companies in Colombo.',
    bodyTa: 'நுண் நிறுவனத்திற்கு, எளிமையான விருப்பம் தனி உரிமையாளராக பதிவு செய்வது. எங்கே: அருகிலுள்ள பிரிவு செயலகம். என்ன தேவை: தேசிய அடையாள அட்டை, முகவரி சான்று, தேர்ந்தெடுக்கப்பட்ட வணிக பெயர். செலவு: சுமார் 500–1,000 ரூபாய். காலம்: பொதுவாக சில நாட்களில் செயலாக்கப்படும். பதிவு செய்வதன் நன்மைகள்: வணிக வங்கி கணக்கு திறக்கலாம், சிறு கடன்களுக்கு விண்ணப்பிக்கலாம்.',
    tags: ['registration', 'business', 'legal', 'sole proprietor', 'government'],
    region: 'all',
    type: 'guide',
  },

  // === FINANCIAL BASICS ===
  {
    id: 'comm-income-profit',
    titleEn: 'Understanding Income vs Profit',
    titleTa: 'வருமானம் vs லாபம் புரிந்துகொள்ளுதல்',
    bodyEn: 'The most common mistake new businesses make is confusing income with profit. Income (revenue) is the total money you receive from sales. Profit is what remains after you subtract ALL costs. Example: You sell 100 palmyra sweets at LKR 50 each. Income = LKR 5,000. Costs: palmyra jaggery LKR 1,500, coconut LKR 500, packaging LKR 300, transport to market LKR 400, phone credit for orders LKR 100, your time (4 hours at LKR 100/hour) = LKR 400. Total costs = LKR 3,200. Profit = LKR 1,800. Always know your PROFIT, not just your income. If your profit is too low, you need to either increase prices, reduce costs, or sell more.',
    bodyTa: 'புதிய வணிகங்கள் செய்யும் மிகப் பொதுவான தவறு வருமானத்தையும் லாபத்தையும் குழப்புவது. வருமானம் என்பது விற்பனையிலிருந்து நீங்கள் பெறும் மொத்த பணம். லாபம் என்பது அனைத்து செலவுகளையும் கழித்த பின் மீதமுள்ளது. உதாரணம்: நீங்கள் 100 பனை இனிப்புகளை ஒன்றுக்கு 50 ரூபாய் வீதம் விற்கிறீர்கள். வருமானம் = 5,000 ரூபாய். செலவுகள்: பனை வெல்லம் 1,500, தேங்காய் 500, பேக்கேஜிங் 300, போக்குவரத்து 400, தொலைபேசி 100, உங்கள் நேரம் 400. மொத்த செலவுகள் = 3,200. லாபம் = 1,800 ரூபாய்.',
    tags: ['finance', 'bookkeeping', 'basics', 'profit', 'income'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'comm-bookkeeping',
    titleEn: 'Simple Bookkeeping with Your Phone',
    titleTa: 'உங்கள் தொலைபேசியில் எளிய கணக்கு வைத்தல்',
    bodyEn: 'You do not need accounting software to track your business finances. A simple Google Sheets spreadsheet works perfectly. Set up three columns: Date, Description (what the money was for), Amount In (+) or Amount Out (-). Record every transaction on the day it happens. At the end of each week, add up your totals. At the end of each month, calculate: total income, total expenses, and profit (income minus expenses). This simple habit will tell you exactly how your business is performing. If you prefer paper, use a small notebook with the same three columns. The key is consistency — record everything, no matter how small.',
    bodyTa: 'உங்கள் வணிக நிதிகளை கண்காணிக்க கணக்கு மென்பொருள் தேவையில்லை. ஒரு எளிய Google Sheets தாள் சரியாக வேலை செய்யும். மூன்று நெடுவரிசைகளை அமையுங்கள்: தேதி, விளக்கம் (பணம் எதற்கு), தொகை வருகிறது (+) அல்லது செல்கிறது (-). ஒவ்வொரு பரிவர்த்தனையையும் அன்றே பதிவு செய்யுங்கள். ஒவ்வொரு வாரமும் இறுதியில், உங்கள் மொத்தங்களை கூட்டுங்கள். ஒவ்வொரு மாதமும் இறுதியில் கணக்கிடுங்கள்: மொத்த வருமானம், மொத்த செலவுகள், லாபம்.',
    tags: ['bookkeeping', 'finance', 'Google Sheets', 'tracking', 'practical'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'comm-credit',
    titleEn: 'Saving and Accessing Credit',
    titleTa: 'சேமிப்பு மற்றும் கடன் பெறுதல்',
    bodyEn: 'Options for saving and borrowing: 1) Cooperative societies — community-owned savings and loan groups. Members save regularly and can borrow at low interest rates. Ask at your local cooperative office. 2) Samurdhi — the government programme provides livelihood grants, savings schemes, and micro-loans for low-income families. Contact your Samurdhi Development Officer at the Grama Niladhari office. 3) Regional Development Bank (RDB) — offers small business loans with lower interest than commercial banks. Branches in most districts. 4) Commercial banks — for larger loans once your business is established. Before borrowing: always compare interest rates, understand the total repayment amount, never borrow more than your business can repay, and have a clear plan for how the money will be used and how it will generate income to repay the loan.',
    bodyTa: 'சேமிப்பு மற்றும் கடன் பெறுவதற்கான விருப்பங்கள்: 1) கூட்டுறவு சங்கங்கள் — சமூக சொந்த சேமிப்பு மற்றும் கடன் குழுக்கள். 2) சமுர்தி — அரசாங்க திட்டம் வாழ்வாதார மானியங்கள், சேமிப்பு திட்டங்கள், நுண்கடன்கள் வழங்குகிறது. 3) பிராந்திய அபிவிருத்தி வங்கி (RDB) — வணிக வங்கிகளை விட குறைந்த வட்டியில் சிறு வணிக கடன்கள். 4) வணிக வங்கிகள் — வணிகம் நிறுவப்பட்டதும் பெரிய கடன்களுக்கு. கடன் பெறுவதற்கு முன்: வட்டி விகிதங்களை ஒப்பிடுங்கள், மொத்த திருப்பிச் செலுத்தும் தொகையை புரிந்துகொள்ளுங்கள்.',
    tags: ['finance', 'loans', 'Samurdhi', 'cooperative', 'credit', 'savings', 'RDB'],
    region: 'all',
    contact: {
      website: 'https://www.rdb.lk',
    },
    type: 'resource',
  },

  // === BUSINESS MODELS ===
  {
    id: 'comm-model-service',
    titleEn: 'Business Model: Service-Based (Beauty, Tailoring, Repairs)',
    titleTa: 'வணிக மாதிரி: சேவை அடிப்படையிலான (அழகு, தையல், பழுதுபார்ப்பு)',
    bodyEn: 'Service businesses are the easiest to start because they require skills, not large investment. Examples: tailoring and alterations, beauty and grooming, mobile phone repair, bicycle and motorbike repair, electrical work, plumbing. To digitise: create a WhatsApp Business profile with your services and prices, ask customers to book via WhatsApp, take before/after photos (with permission) to share on social media, consider accepting mobile payments (FriMi, eZ Cash) alongside cash. Growth tip: offer a loyalty discount for repeat customers and ask satisfied customers for referrals.',
    bodyTa: 'சேவை வணிகங்கள் தொடங்குவதற்கு எளிதானவை ஏனெனில் திறன்கள் தேவை, பெரிய முதலீடு அல்ல. உதாரணங்கள்: தையல் மற்றும் மாற்றங்கள், அழகு மற்றும் ஒப்பனை, கைபேசி பழுதுபார்ப்பு, மிதிவண்டி மற்றும் மோட்டார் பைக் பழுதுபார்ப்பு. டிஜிட்டல் மயமாக்க: உங்கள் சேவைகள் மற்றும் விலைகளுடன் WhatsApp Business சுயவிவரத்தை உருவாக்குங்கள், முன்/பின் புகைப்படங்களை சமூக ஊடகங்களில் பகிருங்கள்.',
    tags: ['business model', 'service', 'tailoring', 'beauty', 'repairs', 'low investment'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'comm-model-food',
    titleEn: 'Business Model: Food & Agriculture',
    titleTa: 'வணிக மாதிரி: உணவு & விவசாயம்',
    bodyEn: 'The food sector is strong in Tamil areas — home-cooked food, preserved foods, fresh produce, and speciality items all have markets. Ideas: traditional sweets and snacks (murukku, kokis, palmyra products), home-cooked meals for delivery (growing demand in urban Jaffna), fresh produce boxes delivered weekly to regular customers, pickles, chutneys, and preserved foods (longer shelf life = wider market), specialty spices and curry powders. To scale: use WhatsApp groups to take orders, deliver on set days to reduce transport costs, partner with local shops to stock your products, and ensure consistent quality — food customers return for reliability.',
    bodyTa: 'உணவுத் துறை தமிழ் பகுதிகளில் வலுவானது — வீட்டில் சமைத்த உணவு, பதப்படுத்தப்பட்ட உணவுகள், புதிய விளைபொருட்கள், சிறப்பு பொருட்கள் அனைத்திற்கும் சந்தைகள் உள்ளன. யோசனைகள்: பாரம்பரிய இனிப்புகள் மற்றும் தின்பண்டங்கள் (முறுக்கு, கோகிஸ், பனை பொருட்கள்), டெலிவரிக்கான வீட்டு சமையல் உணவு, வாராந்திர புதிய விளைபொருள் பெட்டிகள், ஊறுகாய், சட்னிகள், மசாலா பொடிகள்.',
    tags: ['business model', 'food', 'agriculture', 'cooking', 'home business'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'comm-model-cooperative',
    titleEn: 'Business Model: Community Cooperative',
    titleTa: 'வணிக மாதிரி: சமூக கூட்டுறவு',
    bodyEn: 'A cooperative is when a group of people pool their resources, share costs, and divide profits. Why it works: buying materials in bulk is cheaper, shared equipment reduces individual investment, collective bargaining gets better prices from buyers, risk is shared. How to start: gather 10–15 people with a common interest (fishing, farming, craft), agree on rules (how much each person contributes, how decisions are made, how profits are split), register with the Department of Cooperative Development, open a group bank account, and start small — run one collective project before expanding. Successful examples in the North: fishing cooperatives, palmyra processing groups, and women\'s handloom weaving collectives.',
    bodyTa: 'கூட்டுறவு என்பது ஒரு குழு நபர்கள் தங்கள் வளங்களை ஒன்றிணைத்து, செலவுகளை பகிர்ந்து, லாபங்களை பிரிக்கும்போது. ஏன் வேலை செய்கிறது: மொத்தமாக பொருட்கள் வாங்குவது மலிவு, பகிரப்பட்ட உபகரணங்கள் தனிப்பட்ட முதலீட்டை குறைக்கின்றன, கூட்டு பேரம் வாங்குபவர்களிடமிருந்து நல்ல விலைகளைப் பெறுகிறது. எப்படி தொடங்குவது: பொதுவான ஆர்வம் கொண்ட 10–15 பேரை ஒன்று சேர்க்கவும், விதிகளை ஒப்புக்கொள்ளுங்கள், கூட்டுறவு அபிவிருத்தி திணைக்களத்தில் பதிவு செய்யுங்கள்.',
    tags: ['business model', 'cooperative', 'group enterprise', 'community', 'fishing', 'farming'],
    region: 'all',
    type: 'explainer',
  },

  // === COMMUNITY VOICES ===
  {
    id: 'comm-story-priyanka',
    titleEn: 'Priyanka — Tailoring Business, Kilinochchi',
    titleTa: 'பிரியங்கா — தையல் வணிகம், கிளிநொச்சி',
    bodyEn: 'Priyanka started with a single sewing machine gifted by a local NGO after the war. She began tailoring school uniforms for neighbours in her village. Her work was reliable and her prices fair, so word spread. After two years, she saved enough to buy a second machine and hired a young woman from her village as an assistant. Today she employs two assistants and takes orders via WhatsApp. She also teaches basic sewing to teenage girls on Saturdays for a small fee. Her advice: "Start with what people need today, not with a big dream. The dream comes later, once you have proven you can deliver."',
    bodyTa: 'பிரியங்கா போருக்குப் பின் ஒரு உள்ளூர் NGO வழங்கிய ஒரு தையல் இயந்திரத்துடன் தொடங்கினார். தன் கிராமத்தில் அண்டை வீட்டாருக்கு பள்ளி சீருடைகளை தைக்கத் தொடங்கினார். அவரது வேலை நம்பகமானது, விலைகள் நியாயமானவை, எனவே வாய் வார்த்தை பரவியது. இரண்டு ஆண்டுகளுக்குப் பிறகு, இரண்டாவது இயந்திரம் வாங்க சேமித்து, தன் கிராமத்திலிருந்து ஒரு இளம் பெண்ணை உதவியாளராக நியமித்தார். இன்று இரண்டு உதவியாளர்களுடன் WhatsApp மூலம் ஆர்டர்கள் எடுக்கிறார்.',
    tags: ['story', 'tailoring', 'women', 'Kilinochchi', 'success'],
    region: 'north',
    type: 'story',
  },
  {
    id: 'comm-story-rajan',
    titleEn: 'Rajan — Fishing Cooperative, Mullaitivu',
    titleTa: 'ராஜன் — மீன்பிடி கூட்டுறவு, முல்லைத்தீவு',
    bodyEn: 'After the war, Rajan and 12 other fishermen in Mullaitivu had lost their boats and equipment. Individually, none could afford to restart. Together, they formed a cooperative, pooled their savings, and secured a small grant from a diaspora organisation to buy a fibreglass boat and nets. They now fish collectively, share catches proportionally, and have built an informal savings fund. The cooperative also negotiates directly with buyers in Colombo, cutting out middlemen and getting better prices. They recently bought a second boat. Rajan\'s advice: "Alone we struggled. Together we survive. The sea is the same — it is our approach that changed."',
    bodyTa: 'போருக்குப் பிறகு, ராஜன் மற்றும் முல்லைத்தீவில் 12 மீனவர்கள் தங்கள் படகுகளையும் உபகரணங்களையும் இழந்திருந்தனர். தனியாக, யாரும் மீண்டும் தொடங்க முடியவில்லை. ஒன்றாக, கூட்டுறவு அமைத்து, சேமிப்புகளை ஒன்றிணைத்து, ஃபைபர்கிளாஸ் படகு மற்றும் வலைகளை வாங்க புலம்பெயர் நிறுவனத்திடமிருந்து சிறிய மானியம் பெற்றனர். இப்போது கூட்டாக மீன்பிடிக்கிறார்கள், விகிதாசாரமாக பகிர்ந்துகொள்கிறார்கள்.',
    tags: ['story', 'fishing', 'cooperative', 'Mullaitivu', 'success'],
    region: 'north',
    type: 'story',
  },
  {
    id: 'comm-story-kavitha',
    titleEn: 'Kavitha — Home-Cooked Meal Delivery, Jaffna',
    titleTa: 'கவிதா — வீட்டு சமையல் உணவு டெலிவரி, யாழ்ப்பாணம்',
    bodyEn: 'Kavitha is a widow with three school-age children. She was known in her neighbourhood for her excellent cooking. A friend suggested she start selling meals. She began with 5 lunch packets per day, delivered by her eldest son on a bicycle. She marketed through a WhatsApp group her friend created. Within three months, she was making 20 packets per day. She now earns enough to cover school fees and save a little each month. She uses Google Sheets on her phone to track orders and costs. Her advice: "I was afraid to charge for something I did for love. But feeding my children requires money, and there is dignity in earning it through my skill."',
    bodyTa: 'கவிதா பள்ளி செல்லும் மூன்று குழந்தைகளைக் கொண்ட விதவை. அவரது சிறந்த சமையலுக்கு அக்கம்பக்கத்தில் பெயர் பெற்றிருந்தார். ஒரு தோழி உணவு விற்க பரிந்துரைத்தார். நாளுக்கு 5 மதிய உணவு பொட்டலங்களுடன் தொடங்கினார், மூத்த மகன் மிதிவண்டியில் டெலிவரி செய்தார். தோழி உருவாக்கிய WhatsApp குழு மூலம் சந்தைப்படுத்தினார். மூன்று மாதங்களில், நாளுக்கு 20 பொட்டலங்கள் தயாரித்தார்.',
    tags: ['story', 'food', 'women', 'Jaffna', 'delivery', 'success'],
    region: 'north',
    type: 'story',
  },
  {
    id: 'comm-story-muthu',
    titleEn: 'Muthu — Palmyra Products, Vadamarachchi',
    titleTa: 'முத்து — பனை பொருட்கள், வடமராட்சி',
    bodyEn: 'Muthu and five other women in Vadamarachchi formed a small group to process palmyra products — toddy, jaggery, fruit fibre, and woven leaf products. They share a processing space and sell through a local shop and via WhatsApp. A diaspora contact helped them set up a simple Facebook page showcasing their products to Tamil communities abroad. They recently received their first international order — a diaspora customer in Canada wanting authentic palmyra jaggery shipped to Toronto. Muthu says: "The palmyra tree gave our grandmothers a living. It can give us one too, if we find new ways to reach people who miss the taste of home."',
    bodyTa: 'முத்து மற்றும் வடமராட்சியில் ஐந்து பெண்கள் பனை பொருட்களை — கள், வெல்லம், பழ நார், பின்னிய இலை பொருட்கள் — பதப்படுத்த ஒரு சிறு குழுவை உருவாக்கினர். ஒரு செயலாக்க இடத்தை பகிர்ந்து உள்ளூர் கடை மற்றும் WhatsApp மூலம் விற்கிறார்கள். புலம்பெயர் தொடர்பு வெளிநாட்டு தமிழ் சமூகங்களுக்கு தங்கள் பொருட்களை காட்டும் Facebook பக்கத்தை அமைக்க உதவினார்.',
    tags: ['story', 'palmyra', 'women', 'Vadamarachchi', 'export', 'diaspora', 'success'],
    region: 'north',
    type: 'story',
  },
];
