import type { ContentItem } from '@/lib/types';

export const healthContent: ContentItem[] = [
  // === HEALTH AWARENESS TOPICS ===
  {
    id: 'health-diabetes',
    titleEn: 'Diabetes — Know the Signs',
    titleTa: 'நீரிழிவு நோய் — அறிகுறிகளை அறியுங்கள்',
    bodyEn: 'Diabetes is very common in Sri Lanka — nearly 1 in 5 adults is affected. Type 2 diabetes develops gradually and can go unnoticed for years. Warning signs: increased thirst, frequent urination (especially at night), unexplained weight loss, fatigue, blurred vision, slow-healing wounds, and tingling in hands or feet. Risk factors: family history, being overweight, lack of physical activity, and age over 40. If you notice these signs, visit your nearest health centre for a fasting blood sugar test — it is quick, simple, and free at government facilities. Managing diabetes well through diet, exercise, and medication means you can live a full life.',
    bodyTa: 'இலங்கையில் நீரிழிவு நோய் மிகவும் பொதுவானது — 5 பெரியவர்களில் கிட்டத்தட்ட 1 பேர் பாதிக்கப்படுகிறார்கள். வகை 2 நீரிழிவு படிப்படியாக உருவாகி பல ஆண்டுகள் கவனிக்கப்படாமல் போகலாம். எச்சரிக்கை அறிகுறிகள்: அதிகரித்த தாகம், அடிக்கடி சிறுநீர் கழித்தல் (குறிப்பாக இரவில்), விளக்கமுடியாத எடை இழப்பு, சோர்வு, மங்கலான பார்வை, மெதுவாக குணமாகும் காயங்கள், கைகள் அல்லது கால்களில் கூச்ச உணர்வு. இந்த அறிகுறிகளை கவனித்தால், வெறும் வயிற்று இரத்த சர்க்கரை பரிசோதனைக்கு அருகிலுள்ள சுகாதார மையத்திற்கு செல்லுங்கள் — அரசு வசதிகளில் இலவசம்.',
    tags: ['diabetes', 'chronic disease', 'awareness', 'screening', 'prevention'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-hypertension',
    titleEn: 'High Blood Pressure — The Silent Danger',
    titleTa: 'உயர் இரத்த அழுத்தம் — அமைதியான ஆபத்து',
    bodyEn: 'High blood pressure (hypertension) often has no symptoms, which is why it is dangerous. It increases your risk of heart attack, stroke, and kidney disease. Everyone over 30 should have their blood pressure checked at least once a year — it is free at any government health centre. Healthy range: below 120/80. What helps: reduce salt in cooking, eat more vegetables and fruit, walk for 30 minutes daily, reduce stress, limit alcohol, stop smoking. If prescribed medication, take it daily — do not stop when you feel better.',
    bodyTa: 'உயர் இரத்த அழுத்தத்திற்கு (ஹைபர்டென்ஷன்) பெரும்பாலும் அறிகுறிகள் இல்லை, அதனால் இது ஆபத்தானது. இதய அடைப்பு, பக்கவாதம், சிறுநீரக நோய் அபாயத்தை அதிகரிக்கிறது. 30 வயதுக்கு மேற்பட்ட அனைவரும் வருடத்திற்கு குறைந்தது ஒரு முறை இரத்த அழுத்தத்தை சோதிக்க வேண்டும் — எந்த அரசு சுகாதார மையத்திலும் இலவசம். ஆரோக்கிய வரம்பு: 120/80 கீழ். உதவுவது: சமையலில் உப்பை குறையுங்கள், தினமும் 30 நிமிடங்கள் நடையுங்கள், மன அழுத்தத்தை குறையுங்கள்.',
    tags: ['blood pressure', 'hypertension', 'heart disease', 'prevention', 'screening'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-nutrition',
    titleEn: 'Nutrition on a Budget',
    titleTa: 'குறைந்த வரவு செலவில் ஊட்டச்சத்து',
    bodyEn: 'Good nutrition does not require expensive food. Affordable and nutritious foods available in Sri Lanka: dhal (protein and iron), eggs (complete protein — aim for 3–4 per week), dark green leafy vegetables like murunga and keerai (vitamins and iron), jak fruit and breadfruit (energy), coconut (healthy fats), local fish (protein and omega-3), brown rice instead of white where possible. Tips: eat a variety of colours each day, include a protein source at every meal, limit sugar and processed food, drink clean water regularly. Children under 5 and pregnant women have the highest nutrition needs — prioritise them.',
    bodyTa: 'நல்ல ஊட்டச்சத்துக்கு விலையுயர்ந்த உணவு தேவையில்லை. இலங்கையில் கிடைக்கும் மலிவான மற்றும் சத்தான உணவுகள்: பருப்பு (புரதம் மற்றும் இரும்பு), முட்டைகள் (வாரத்திற்கு 3–4 குறிவை), முருங்கை மற்றும் கீரை போன்ற கரும் பச்சை இலை காய்கறிகள், பலா மற்றும் ஈரப்பலா (ஆற்றல்), தேங்காய் (ஆரோக்கிய கொழுப்புகள்), உள்ளூர் மீன் (புரதம் மற்றும் ஒமேகா-3). குறிப்புகள்: ஒவ்வொரு நாளும் பல்வேறு நிறங்களை உண்ணுங்கள், ஒவ்வொரு உணவிலும் புரத ஆதாரத்தை சேர்க்கவும்.',
    tags: ['nutrition', 'diet', 'affordable', 'food', 'children', 'pregnancy'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-dental',
    titleEn: 'Dental Health — Prevention Is Free',
    titleTa: 'பல் சுகாதாரம் — தடுப்பு இலவசம்',
    bodyEn: 'Dental problems are among the most common health issues and often the most neglected. Basic prevention: brush teeth twice daily (morning and before bed), use fluoride toothpaste, limit sugary food and drinks, do not use teeth to open bottles or crack nuts. Warning signs that need attention: persistent toothache, bleeding gums, loose teeth, bad breath that does not go away, or swelling in the face. Government dental clinics are available at most divisional hospitals — treatment is free. Do not ignore dental pain — infections can spread and become serious.',
    bodyTa: 'பல் பிரச்சனைகள் மிகவும் பொதுவான சுகாதார பிரச்சனைகளில் ஒன்று, பெரும்பாலும் புறக்கணிக்கப்படுகிறது. அடிப்படை தடுப்பு: தினமும் இரு முறை பல் துலக்குங்கள் (காலையும் படுக்கைக்கு முன்பும்), ஃப்ளோரைடு பற்பசை பயன்படுத்துங்கள், சர்க்கரை உணவு மற்றும் பானங்களை குறையுங்கள். கவனிக்க வேண்டிய எச்சரிக்கை அறிகுறிகள்: தொடர்ந்த பல்வலி, ஈறுகளில் இரத்தம், தளர்ந்த பற்கள். அரசு பல் மருத்துவ நிலையங்கள் பெரும்பாலான பிரிவு மருத்துவமனைகளில் கிடைக்கும் — சிகிச்சை இலவசம்.',
    tags: ['dental', 'oral health', 'prevention', 'free treatment'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-maternal',
    titleEn: 'Maternal Health — Your Pregnancy, Your Rights',
    titleTa: 'தாய்மை சுகாதாரம் — உங்கள் கர்ப்பம், உங்கள் உரிமைகள்',
    bodyEn: 'Every pregnant woman in Sri Lanka is entitled to free antenatal care through the MOH system. As soon as you know you are pregnant, visit your local MOH clinic to register. You will receive: regular check-ups by the Public Health Midwife (PHM), blood tests and urine tests, iron and folic acid supplements (free), tetanus vaccination, ultrasound scans at the hospital, delivery at a government hospital (free), and postnatal visits by the PHM. Your PHM is your main contact — she will visit your home. If you experience severe headaches, sudden swelling, bleeding, or reduced baby movement, go to hospital immediately. You have the right to respectful care and to have a companion during labour.',
    bodyTa: 'இலங்கையில் ஒவ்வொரு கர்ப்பிணிப் பெண்ணுக்கும் MOH முறை மூலம் இலவச பிரசவ முன் பராமரிப்பு உரிமை உண்டு. கர்ப்பமாக இருப்பதை அறிந்தவுடன், பதிவு செய்ய உள்ளூர் MOH மருத்துவ நிலையத்திற்கு செல்லுங்கள். பெறுவீர்கள்: பொது சுகாதார மருத்துவச்சியால் (PHM) வழக்கமான பரிசோதனைகள், இரத்த மற்றும் சிறுநீர் பரிசோதனைகள், இரும்பு மற்றும் ஃபோலிக் அமில மாத்திரைகள் (இலவசம்), டெட்டனஸ் தடுப்பூசி, அல்ட்ராசவுண்ட் ஸ்கேன்கள், அரசு மருத்துவமனையில் பிரசவம் (இலவசம்).',
    tags: ['maternal', 'pregnancy', 'women', 'antenatal', 'midwife', 'rights', 'free care'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-menstrual',
    titleEn: 'Menstrual Health — Breaking the Silence',
    titleTa: 'மாதவிடாய் சுகாதாரம் — மௌனத்தை உடைத்தல்',
    bodyEn: 'Menstruation is a normal, healthy part of life — not something to be ashamed of. A normal cycle is 21–35 days. Seek medical advice if: periods are extremely painful and stop you from daily activities, bleeding is very heavy (soaking through a pad every hour), periods stop for more than 3 months (if not pregnant), or you bleed between periods. Hygiene during menstruation: change pads or cloth regularly (every 4–6 hours), wash reusable cloth thoroughly and dry in sunlight, wash hands before and after changing. Affordable sanitary products are available at government pharmacies. Schools should allow girls to use the bathroom when needed and should not restrict activities during menstruation.',
    bodyTa: 'மாதவிடாய் என்பது வாழ்க்கையின் இயல்பான, ஆரோக்கியமான பகுதி — வெட்கப்பட வேண்டிய ஒன்றல்ல. சாதாரண சுழற்சி 21–35 நாட்கள். மருத்துவ ஆலோசனை பெறுங்கள்: மாதவிடாய் மிகவும் வலிமையானதாக இருந்து அன்றாட நடவடிக்கைகளை நிறுத்தினால், இரத்தப்போக்கு மிக அதிகமாக இருந்தால், 3 மாதங்களுக்கு மேல் மாதவிடாய் நின்றால் (கர்ப்பமல்ல என்றால்). சுகாதாரம்: பேட்கள் அல்லது துணியை தொடர்ந்து மாற்றுங்கள் (ஒவ்வொரு 4–6 மணி நேரமும்).',
    tags: ['menstrual health', 'women', 'hygiene', 'taboo', 'awareness'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'health-menopause',
    titleEn: 'Understanding Menopause',
    titleTa: 'மாதவிடாய் நிறுத்தத்தைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Menopause typically occurs between ages 45–55 when periods stop permanently. It is a natural transition, not a disease. Common experiences: hot flushes, night sweats, mood changes, difficulty sleeping, joint pain, and changes in libido. These symptoms are caused by changing hormone levels and usually improve over time. What helps: stay physically active, eat well, stay cool (cotton clothing, fans), maintain social connections, and talk to your doctor if symptoms significantly affect your quality of life. Hormone replacement therapy is available in Sri Lanka for severe symptoms — discuss with a gynaecologist.',
    bodyTa: 'மாதவிடாய் நிறுத்தம் பொதுவாக 45–55 வயதுக்கு இடையில் மாதவிடாய் நிரந்தரமாக நிறுத்தும்போது ஏற்படுகிறது. இது இயற்கையான மாற்றம், நோய் அல்ல. பொதுவான அனுபவங்கள்: வெப்ப அலைகள், இரவு வியர்வை, மனநிலை மாற்றங்கள், தூக்கமின்மை, மூட்டு வலி. இந்த அறிகுறிகள் மாறும் ஹார்மோன் அளவுகளால் ஏற்படுகின்றன, பொதுவாக காலப்போக்கில் மேம்படும்.',
    tags: ['menopause', 'women', 'hormones', 'ageing', 'health'],
    region: 'all',
    type: 'explainer',
  },

  // === HOSPITALS & HEALTHCARE FACILITIES ===
  {
    id: 'health-hosp-jaffna',
    titleEn: 'Jaffna Teaching Hospital',
    titleTa: 'யாழ்ப்பாண போதனா மருத்துவமனை',
    bodyEn: 'The main referral hospital for the Northern Province. Specialist departments: surgery, medicine, obstetrics & gynaecology, paediatrics, ENT, ophthalmology, orthopaedics, psychiatry, and dental. Emergency department open 24/7. All services free of charge. Tamil is the primary working language. Blood bank available. CT scan and basic laboratory services on site.',
    bodyTa: 'வடக்கு மாகாணத்தின் முக்கிய பரிந்துரை மருத்துவமனை. நிபுணர் பிரிவுகள்: அறுவை சிகிச்சை, மருத்துவம், மகப்பேறு & பெண்கள் நோய், குழந்தை மருத்துவம், ENT, கண், எலும்பு, மனநலம், பல். அவசர சிகிச்சை பிரிவு 24/7 திறந்திருக்கும். அனைத்து சேவைகளும் இலவசம். தமிழ் முதன்மை மொழி.',
    tags: ['hospital', 'emergency', 'Northern Province', 'Jaffna', 'specialist', 'free'],
    region: 'north',
    contact: {
      phone: '+94 21 222 2261',
      website: 'https://www.health.gov.lk',
      address: 'Hospital Road, Jaffna',
    },
    type: 'resource',
  },
  {
    id: 'health-hosp-batticaloa',
    titleEn: 'Batticaloa Teaching Hospital',
    titleTa: 'மட்டக்களப்பு போதனா மருத்துவமனை',
    bodyEn: 'The main referral hospital for the Eastern Province. Specialist departments include surgery, medicine, obstetrics, paediatrics, orthopaedics, and psychiatry. Emergency department open 24/7. Expanded facilities since post-war reconstruction. Tamil and Sinhala-speaking staff. All services free of charge.',
    bodyTa: 'கிழக்கு மாகாணத்தின் முக்கிய பரிந்துரை மருத்துவமனை. அறுவை சிகிச்சை, மருத்துவம், மகப்பேறு, குழந்தை மருத்துவம், எலும்பு, மனநலம் ஆகிய நிபுணர் பிரிவுகள். அவசர சிகிச்சை பிரிவு 24/7 திறந்திருக்கும். போருக்குப் பிந்தைய புனரமைப்புக்குப் பின் விரிவாக்கப்பட்ட வசதிகள். அனைத்து சேவைகளும் இலவசம்.',
    tags: ['hospital', 'emergency', 'Eastern Province', 'Batticaloa', 'specialist', 'free'],
    region: 'east',
    contact: {
      phone: '+94 65 222 2261',
      website: 'https://www.health.gov.lk',
      address: 'Batticaloa',
    },
    type: 'resource',
  },
  {
    id: 'health-hosp-kilinochchi',
    titleEn: 'Kilinochchi District General Hospital',
    titleTa: 'கிளிநொச்சி மாவட்ட பொது மருத்துவமனை',
    bodyEn: 'District-level hospital serving Kilinochchi district. Provides general medical and surgical services, maternity care, and outpatient clinics. For specialist care, patients are referred to Jaffna Teaching Hospital. 24/7 emergency services available.',
    bodyTa: 'கிளிநொச்சி மாவட்டத்திற்கு சேவை செய்யும் மாவட்ட மட்ட மருத்துவமனை. பொது மருத்துவ மற்றும் அறுவை சிகிச்சை சேவைகள், தாய்மை பராமரிப்பு, வெளிநோயாளி மருத்துவ நிலையங்கள் வழங்குகிறது. நிபுணர் பராமரிப்புக்கு, நோயாளிகள் யாழ்ப்பாண போதனா மருத்துவமனைக்கு பரிந்துரைக்கப்படுகிறார்கள்.',
    tags: ['hospital', 'Kilinochchi', 'Northern Province', 'emergency'],
    region: 'north',
    contact: {
      phone: '+94 21 228 3261',
      website: 'https://www.health.gov.lk',
      address: 'Kilinochchi',
    },
    type: 'resource',
  },
  {
    id: 'health-hosp-mullaitivu',
    titleEn: 'Mullaitivu District General Hospital',
    titleTa: 'முல்லைத்தீவு மாவட்ட பொது மருத்துவமனை',
    bodyEn: 'Serves Mullaitivu district. Rebuilt after the conflict with improved facilities. General medical, surgical, and maternity services. Outpatient department and pharmacy on site. Complex cases referred to Jaffna Teaching Hospital.',
    bodyTa: 'முல்லைத்தீவு மாவட்டத்திற்கு சேவை செய்கிறது. மோதலுக்குப் பின் மேம்படுத்தப்பட்ட வசதிகளுடன் மீண்டும் கட்டப்பட்டது. பொது மருத்துவ, அறுவை சிகிச்சை மற்றும் தாய்மை சேவைகள். வெளிநோயாளி பிரிவு மற்றும் மருந்தகம்.',
    tags: ['hospital', 'Mullaitivu', 'Northern Province'],
    region: 'north',
    contact: {
      phone: '+94 21 229 0261',
      website: 'https://www.health.gov.lk',
      address: 'Mullaitivu',
    },
    type: 'resource',
  },
  {
    id: 'health-hosp-trinco',
    titleEn: 'Trincomalee General Hospital',
    titleTa: 'திருகோணமலை பொது மருத்துவமனை',
    bodyEn: 'Serves Trincomalee district in the Eastern Province. General and specialist services available. Tamil and Sinhala-speaking staff. Emergency department open 24/7.',
    bodyTa: 'கிழக்கு மாகாணத்தில் திருகோணமலை மாவட்டத்திற்கு சேவை செய்கிறது. பொது மற்றும் நிபுணர் சேவைகள் கிடைக்கும். தமிழ் மற்றும் சிங்கள மொழி பேசும் ஊழியர்கள். அவசர சிகிச்சை பிரிவு 24/7 திறந்திருக்கும்.',
    tags: ['hospital', 'Trincomalee', 'Eastern Province', 'emergency'],
    region: 'east',
    contact: {
      phone: '+94 26 222 2261',
      website: 'https://www.health.gov.lk',
      address: 'Trincomalee',
    },
    type: 'resource',
  },

  // === PEER HEALTH GUIDE ===
  {
    id: 'health-guide-1',
    titleEn: 'Peer Health Supporter Guide',
    titleTa: 'சக சுகாதார ஆதரவாளர் வழிகாட்டி',
    bodyEn: 'When you help a neighbour or family member navigate the health system, you are performing a vital community service. This guide covers: how to help someone prepare for a hospital visit (bring identity card, any previous test results, a list of current medications, and a companion), how to understand a prescription (ask the pharmacist to explain each medication, its purpose, dosage, and timing), questions to ask the doctor (what is the diagnosis, what are the treatment options, what are the side effects, when should we come back), when to accompany someone versus encouraging independence, and recognising when a condition needs urgent attention. Remember: you are not expected to be a doctor — your role is to support, not diagnose.',
    bodyTa: 'ஒரு அண்டை வீட்டார் அல்லது குடும்ப உறுப்பினருக்கு சுகாதார முறையில் வழிசெலுத்த உதவும்போது, நீங்கள் முக்கியமான சமூக சேவையை செய்கிறீர்கள். இந்த வழிகாட்டி உள்ளடக்குவது: மருத்துவமனை வருகைக்கு தயாராக உதவுவது (அடையாள அட்டை, முந்தைய பரிசோதனை முடிவுகள், தற்போதைய மருந்துகளின் பட்டியல் கொண்டு வரவும்), மருந்துச் சீட்டை புரிந்துகொள்வது, மருத்துவரிடம் கேட்க வேண்டிய கேள்விகள்.',
    tags: ['peer support', 'health literacy', 'training', 'hospital visits', 'prescriptions'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'health-guide-2',
    titleEn: 'Understanding the Sri Lankan Health System',
    titleTa: 'இலங்கை சுகாதார முறையைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Sri Lanka\'s public healthcare is free at the point of use. The system works in tiers: 1) MOH (Medical Officer of Health) clinics — your first contact for preventive care, vaccinations, maternal care, and health education. Every area has a designated MOH. 2) Divisional/Rural Hospitals — basic inpatient and outpatient care, minor surgery. 3) District General Hospitals — specialist services, more complex care. 4) Teaching Hospitals — the most specialised care (Jaffna, Batticaloa, Colombo). How to navigate: for non-emergencies, start at the MOH or divisional hospital. They will refer you upward if needed. For emergencies, go directly to the nearest hospital with an emergency department. You do not need insurance — everything is free. Private healthcare is available but can be expensive.',
    bodyTa: 'இலங்கையின் பொது சுகாதாரம் பயன்படுத்தும் இடத்தில் இலவசம். முறை அடுக்குகளில் செயல்படுகிறது: 1) MOH மருத்துவ நிலையங்கள் — தடுப்பு பராமரிப்பு, தடுப்பூசிகள், தாய்மை பராமரிப்பு. 2) பிரிவு/கிராம மருத்துவமனைகள் — அடிப்படை உள்நோயாளி மற்றும் வெளிநோயாளி பராமரிப்பு. 3) மாவட்ட பொது மருத்துவமனைகள் — நிபுணர் சேவைகள். 4) போதனா மருத்துவமனைகள் — மிகவும் நிபுணத்துவ பராமரிப்பு.',
    tags: ['health system', 'MOH', 'hospital', 'how it works', 'free healthcare', 'guide'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
];
