import type { ContentItem } from '@/lib/types';

export const sendContent: ContentItem[] = [
  {
    id: 'send-1',
    titleEn: 'Understanding Autism',
    titleTa: 'மன இயல்புத்தன்மையைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Autism is a developmental difference that affects how a person communicates and experiences the world. Children with autism may find social situations challenging, prefer routines, or have strong interests in specific topics. Early support helps children develop their strengths.',
    bodyTa: 'மன இயல்புத்தன்மை என்பது ஒரு நபர் எவ்வாறு தொடர்புகொள்கிறார் மற்றும் உலகத்தை அனுபவிக்கிறார் என்பதை பாதிக்கும் ஒரு வளர்ச்சி வேறுபாடு. மன இயல்புத்தன்மை கொண்ட குழந்தைகள் சமூக சூழ்நிலைகளை சவாலாக கருதலாம், வழக்கமான செயல்முறைகளை விரும்பலாம், அல்லது குறிப்பிட்ட தலைப்புகளில் வலுவான ஆர்வங்களை கொண்டிருக்கலாம். ஆரம்ப ஆதரவு குழந்தைகளின் வலிமைகளை வளர்க்க உதவுகிறது.',
    tags: ['autism', 'children', 'awareness'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-2',
    titleEn: 'Supporting a Child with Dyslexia at Home',
    titleTa: 'வீட்டில் டிஸ்லெக்சியா கொண்ட குழந்தையை ஆதரித்தல்',
    bodyEn: 'Dyslexia makes reading and writing more difficult, but it does not affect intelligence. Read aloud with your child daily. Use multi-sensory approaches — tracing letters in sand, using coloured paper. Be patient and celebrate small wins. Your child is working harder than you may realise.',
    bodyTa: 'டிஸ்லெக்சியா வாசிப்பையும் எழுதுவதையும் கடினமாக்குகிறது, ஆனால் இது புத்திசாலித்தனத்தை பாதிக்காது. உங்கள் குழந்தையுடன் தினமும் சத்தமாக படியுங்கள். பல உணர்வு அணுகுமுறைகளைப் பயன்படுத்துங்கள் — மணலில் எழுத்துக்களை வரைதல், வண்ண காகிதத்தைப் பயன்படுத்துதல். பொறுமையாக இருங்கள், சிறிய வெற்றிகளை கொண்டாடுங்கள்.',
    tags: ['dyslexia', 'home support', 'children'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'send-3',
    titleEn: 'Cerebral Palsy Alliance — Sri Lanka',
    titleTa: 'பெருமூளை வாதம் கூட்டமைப்பு — இலங்கை',
    bodyEn: 'The Cerebral Palsy Alliance provides physiotherapy, occupational therapy, and family support for children and adults with cerebral palsy in Sri Lanka. They offer home visit programmes in the Northern and Eastern Provinces.',
    bodyTa: 'பெருமூளை வாதம் கூட்டமைப்பு இலங்கையில் பெருமூளை வாதம் கொண்ட குழந்தைகள் மற்றும் பெரியவர்களுக்கு இயன்முறை சிகிச்சை, தொழில் சிகிச்சை மற்றும் குடும்ப ஆதரவை வழங்குகிறது. வடக்கு மற்றும் கிழக்கு மாகாணங்களில் வீட்டுக்கு வருகை நிரல்களை வழங்குகிறார்கள்.',
    tags: ['cerebral palsy', 'physiotherapy', 'disability'],
    region: 'national',
    contact: {
      phone: '+94 11 269 4132',
      email: 'info@cpasl.org',
      address: 'Colombo, Sri Lanka',
    },
    type: 'resource',
  },
  {
    id: 'send-4',
    titleEn: 'Advocating for Your Child in School',
    titleTa: 'பள்ளியில் உங்கள் குழந்தைக்காக வாதாடுதல்',
    bodyEn: 'Every child has the right to education. If your child has additional needs, speak with the class teacher and school principal. Ask what support is available. Request a meeting to discuss your child\'s needs. In Sri Lanka, inclusive education policies mean schools should make reasonable accommodations.',
    bodyTa: 'ஒவ்வொரு குழந்தைக்கும் கல்வி பெறும் உரிமை உண்டு. உங்கள் குழந்தைக்கு கூடுதல் தேவைகள் இருந்தால், வகுப்பு ஆசிரியர் மற்றும் பள்ளி அதிபரிடம் பேசுங்கள். என்ன ஆதரவு கிடைக்கும் என்று கேளுங்கள். உங்கள் குழந்தையின் தேவைகளை விவாதிக்க ஒரு சந்திப்பை கோருங்கள்.',
    tags: ['advocacy', 'school', 'rights'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'send-5',
    titleEn: 'Hearing and Vision Impairment Support',
    titleTa: 'கேள்வி மற்றும் பார்வை குறைபாடு ஆதரவு',
    bodyEn: 'If you suspect your child has difficulty hearing or seeing, visit your nearest MOH clinic for a screening. Early detection makes a significant difference. The Jaffna Teaching Hospital has audiology and ophthalmology departments serving the Northern Province.',
    bodyTa: 'உங்கள் குழந்தைக்கு கேட்பதில் அல்லது பார்ப்பதில் சிரமம் இருப்பதாக நீங்கள் சந்தேகித்தால், அருகிலுள்ள MOH மருத்துவ நிலையத்தில் பரிசோதனைக்கு செல்லுங்கள். ஆரம்ப கண்டறிதல் குறிப்பிடத்தக்க வேறுபாட்டை ஏற்படுத்துகிறது. யாழ்ப்பாண போதனா மருத்துவமனையில் வடக்கு மாகாணத்திற்கு சேவை செய்யும் செவியியல் மற்றும் கண் மருத்துவ பிரிவுகள் உள்ளன.',
    tags: ['hearing', 'vision', 'screening', 'children'],
    region: 'north',
    contact: {
      phone: '+94 21 222 2261',
      address: 'Jaffna Teaching Hospital, Jaffna',
    },
    type: 'resource',
  },
];
