import type { ContentItem } from '@/lib/types';

export const sendContent: ContentItem[] = [
  // === UNDERSTANDING CONDITIONS ===
  {
    id: 'send-autism',
    titleEn: 'Understanding Autism',
    titleTa: 'மன இயல்புத்தன்மையைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Autism is a developmental difference that affects how a person communicates and experiences the world. It is not a disease — it is a different way of being. Children with autism may: find social situations challenging, prefer routines and become upset by changes, have intense interests in specific topics, be sensitive to sounds, lights, or textures, or communicate in ways that are different from other children. Autism is a spectrum — every person with autism is different. Some need significant daily support, while others need minimal help. Early identification and appropriate support help children develop their strengths and build confidence.',
    bodyTa: 'மன இயல்புத்தன்மை என்பது ஒரு நபர் எவ்வாறு தொடர்புகொள்கிறார் மற்றும் உலகத்தை அனுபவிக்கிறார் என்பதை பாதிக்கும் ஒரு வளர்ச்சி வேறுபாடு. இது ஒரு நோய் அல்ல — இது ஒரு வேறுபட்ட இருப்பு முறை. மன இயல்புத்தன்மை கொண்ட குழந்தைகள்: சமூக சூழ்நிலைகளை சவாலாக காணலாம், வழக்கமான செயல்முறைகளை விரும்பி மாற்றங்களால் வருத்தமடையலாம், குறிப்பிட்ட தலைப்புகளில் தீவிர ஆர்வங்களை கொண்டிருக்கலாம், ஒலிகள், விளக்குகள் அல்லது அமைப்புகளுக்கு உணர்திறனாக இருக்கலாம். மன இயல்புத்தன்மை ஒரு நிறமாலை — ஒவ்வொரு நபரும் வேறுபட்டவர்.',
    tags: ['autism', 'children', 'awareness', 'developmental', 'neurodiversity'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-dyslexia',
    titleEn: 'Understanding Dyslexia',
    titleTa: 'டிஸ்லெக்சியாவைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Dyslexia makes reading, writing, and spelling more difficult, but it does not affect intelligence. A child with dyslexia may be very creative, excellent at problem-solving, or talented in art, music, or sport — but struggle with written work. Signs include: mixing up letters (b/d, p/q), reading slowly, difficulty copying from the board, avoiding reading aloud, and inconsistent spelling. Dyslexia is common — it affects roughly 1 in 10 people. With the right support, children with dyslexia can achieve as well as anyone else. The key is early identification and adapting how information is taught.',
    bodyTa: 'டிஸ்லெக்சியா வாசிப்பு, எழுதுதல் மற்றும் எழுத்துப்பிழையை கடினமாக்குகிறது, ஆனால் இது புத்திசாலித்தனத்தை பாதிக்காது. டிஸ்லெக்சியா கொண்ட குழந்தை மிகவும் படைப்பாற்றல் மிக்கதாக, சிக்கல் தீர்வில் சிறந்ததாக, கலை, இசை அல்லது விளையாட்டில் திறமையானதாக இருக்கலாம் — ஆனால் எழுத்து வேலையில் போராடலாம். அறிகுறிகளில் அடங்கும்: எழுத்துக்களை கலப்பது, மெதுவாக படிப்பது, பலகையிலிருந்து நகலெடுப்பதில் சிரமம். டிஸ்லெக்சியா பொதுவானது — 10 பேரில் 1 பேரை பாதிக்கிறது.',
    tags: ['dyslexia', 'reading', 'learning difficulty', 'children', 'awareness'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-hearing',
    titleEn: 'Hearing Impairment — What Families Need to Know',
    titleTa: 'கேள்வி குறைபாடு — குடும்பங்கள் தெரிந்துகொள்ள வேண்டியவை',
    bodyEn: 'Hearing impairment ranges from mild to profound. Signs in babies: not startling at loud sounds, not turning towards voices by 6 months, not babbling by 12 months. Signs in older children: sitting close to the TV, asking "what?" frequently, speaking loudly, difficulty following instructions. If you suspect hearing difficulty, visit your nearest MOH clinic or the ENT department at a Teaching Hospital. Hearing aids and speech therapy can make a significant difference. In Sri Lanka, government hospitals provide hearing assessments free of charge. The Jaffna Teaching Hospital has an audiology department.',
    bodyTa: 'கேள்வி குறைபாடு லேசானது முதல் ஆழமானது வரை இருக்கும். குழந்தைகளில் அறிகுறிகள்: உரத்த சத்தங்களில் திடுக்கிடாமை, 6 மாதங்களில் குரல்களை நோக்கி திரும்பாமை, 12 மாதங்களில் மழலை பேசாமை. பெரிய குழந்தைகளில்: TV-க்கு அருகில் அமர்வது, அடிக்கடி "என்ன?" என்று கேட்பது, உரத்தமாக பேசுவது. கேள்வி சிரமத்தை சந்தேகித்தால், அருகிலுள்ள MOH மருத்துவ நிலையம் அல்லது போதனா மருத்துவமனையின் ENT பிரிவுக்கு செல்லுங்கள்.',
    tags: ['hearing', 'impairment', 'children', 'screening', 'audiology'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-vision',
    titleEn: 'Vision Impairment — Early Signs and Support',
    titleTa: 'பார்வை குறைபாடு — ஆரம்ப அறிகுறிகள் மற்றும் ஆதரவு',
    bodyEn: 'Vision problems can affect learning and development if not identified early. Signs: holding books very close or very far, squinting, frequent headaches, difficulty reading the board at school, bumping into things, one eye turning in or out. Free vision screening is available at MOH clinics and government hospitals. The ophthalmology departments at Jaffna and Batticaloa Teaching Hospitals can assess and treat childhood vision problems. Glasses are provided free at government hospitals for children under 16.',
    bodyTa: 'பார்வை பிரச்சனைகள் ஆரம்பத்தில் கண்டறியப்படாவிட்டால் கற்றல் மற்றும் வளர்ச்சியை பாதிக்கலாம். அறிகுறிகள்: புத்தகங்களை மிக அருகில் அல்லது மிகத் தொலைவில் பிடிப்பது, கண்களை சுருக்குவது, அடிக்கடி தலைவலி, பள்ளியில் பலகையை படிப்பதில் சிரமம். MOH மருத்துவ நிலையங்கள் மற்றும் அரசு மருத்துவமனைகளில் இலவச பார்வை பரிசோதனை கிடைக்கும்.',
    tags: ['vision', 'impairment', 'children', 'screening', 'ophthalmology'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-cerebral-palsy',
    titleEn: 'Understanding Cerebral Palsy',
    titleTa: 'பெருமூளை வாதத்தைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Cerebral palsy affects movement and muscle coordination. It is caused by brain damage before, during, or shortly after birth. Each child is affected differently — some walk independently, others use wheelchairs. Cerebral palsy does not get worse over time, and many people with cerebral palsy lead full, independent lives. Physiotherapy, occupational therapy, and speech therapy are key supports. Start early — the younger the child, the more effective therapy is. Regular stretching and exercise help maintain mobility.',
    bodyTa: 'பெருமூளை வாதம் இயக்கம் மற்றும் தசை ஒருங்கிணைப்பை பாதிக்கிறது. பிறப்புக்கு முன், போது அல்லது சீக்கிரம் ஏற்படும் மூளை சேதத்தால் ஏற்படுகிறது. ஒவ்வொரு குழந்தையும் வித்தியாசமாக பாதிக்கப்படுகிறது — சிலர் சுதந்திரமாக நடக்கிறார்கள், மற்றவர்கள் சக்கர நாற்காலிகளை பயன்படுத்துகிறார்கள். பெருமூளை வாதம் காலப்போக்கில் மோசமாகாது, பலர் முழுமையான, சுதந்திரமான வாழ்க்கையை வாழ்கிறார்கள்.',
    tags: ['cerebral palsy', 'physical disability', 'physiotherapy', 'children'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'send-intellectual',
    titleEn: 'Understanding Intellectual Disability',
    titleTa: 'அறிவுசார் குறைபாட்டைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'Intellectual disability means a person learns more slowly and may find complex tasks harder. It varies widely — some people need support with daily living, while others live independently with occasional help. Signs in children: late developmental milestones (walking, talking), difficulty understanding instructions, needing more time to learn new skills. People with intellectual disabilities have feelings, preferences, and rights just like everyone else. With patience, clear communication, and the right support, they can participate fully in community life.',
    bodyTa: 'அறிவுசார் குறைபாடு என்பது ஒரு நபர் மெதுவாக கற்றுக்கொள்கிறார் மற்றும் சிக்கலான பணிகளை கடினமாக காணலாம் என்பதாகும். இது பரவலாக மாறுபடுகிறது — சிலருக்கு அன்றாட வாழ்க்கையில் ஆதரவு தேவை, மற்றவர்கள் எப்போதாவது உதவியுடன் சுதந்திரமாக வாழ்கிறார்கள். குழந்தைகளில் அறிகுறிகள்: தாமதமான வளர்ச்சி மைல்கற்கள் (நடத்தல், பேசுதல்), அறிவுறுத்தல்களைப் புரிந்துகொள்வதில் சிரமம்.',
    tags: ['intellectual disability', 'learning', 'developmental', 'inclusion'],
    region: 'all',
    type: 'explainer',
  },

  // === HOME SUPPORT GUIDES ===
  {
    id: 'send-home-autism',
    titleEn: 'Supporting a Child with Autism at Home',
    titleTa: 'வீட்டில் மன இயல்புத்தன்மை கொண்ட குழந்தையை ஆதரித்தல்',
    bodyEn: 'Create a predictable environment: use visual schedules (pictures showing the order of daily activities), give advance warning before transitions ("in 5 minutes we will eat"), keep noise levels manageable, and create a quiet space the child can go to when overwhelmed. Communicate clearly: use short sentences, give one instruction at a time, allow extra time for responses. Build on their interests — if they love trains, use trains to teach counting. Celebrate what they can do, not what they cannot. Connect with other families — you are not alone in this journey.',
    bodyTa: 'கணிக்கக்கூடிய சூழலை உருவாக்குங்கள்: காட்சி அட்டவணைகளை பயன்படுத்துங்கள் (அன்றாட நடவடிக்கைகளின் வரிசையை காட்டும் படங்கள்), மாற்றங்களுக்கு முன் முன்கூட்டிய எச்சரிக்கை கொடுங்கள் ("5 நிமிடங்களில் சாப்பிடுவோம்"), சத்த அளவை நிர்வகிக்கக்கூடியதாக வையுங்கள், அதிகப்படியான சூழ்நிலையில் குழந்தை செல்லக்கூடிய அமைதியான இடத்தை உருவாக்குங்கள். தெளிவாக தொடர்பு கொள்ளுங்கள்: குறுகிய வாக்கியங்களை பயன்படுத்துங்கள், ஒரு நேரத்தில் ஒரு அறிவுறுத்தல் கொடுங்கள்.',
    tags: ['autism', 'home support', 'parenting', 'practical tips', 'visual schedules'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'send-home-dyslexia',
    titleEn: 'Supporting a Child with Dyslexia at Home',
    titleTa: 'வீட்டில் டிஸ்லெக்சியா கொண்ட குழந்தையை ஆதரித்தல்',
    bodyEn: 'Read aloud with your child every day — even 10 minutes makes a difference. Use multi-sensory approaches: trace letters in sand, form words with clay or rice, use coloured paper to reduce glare. Break homework into small chunks with breaks in between. Never compare them to siblings or classmates. Use audiobooks and videos alongside written materials. Let them dictate answers while you write — the ideas matter more than the handwriting. Praise effort, not just results. Your patience and belief in them is the most powerful support you can give.',
    bodyTa: 'ஒவ்வொரு நாளும் உங்கள் குழந்தையுடன் சத்தமாக படியுங்கள் — 10 நிமிடங்கள் கூட வேறுபாட்டை ஏற்படுத்தும். பல உணர்வு அணுகுமுறைகளை பயன்படுத்துங்கள்: மணலில் எழுத்துக்களை வரையுங்கள், களிமண் அல்லது அரிசியில் வார்த்தைகளை உருவாக்குங்கள், பளிச்சை குறைக்க வண்ண காகிதத்தை பயன்படுத்துங்கள். வீட்டுப்பாடத்தை இடைவெளிகளுடன் சிறிய பகுதிகளாக பிரியுங்கள். ஒருபோதும் உடன்பிறப்புகள் அல்லது வகுப்புத்தோழர்களுடன் ஒப்பிடாதீர்கள்.',
    tags: ['dyslexia', 'home support', 'reading', 'parenting', 'multi-sensory'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'send-home-general',
    titleEn: 'General Tips for Supporting Any Child with SEND',
    titleTa: 'SEND கொண்ட எந்த குழந்தையையும் ஆதரிப்பதற்கான பொதுவான குறிப்புகள்',
    bodyEn: 'Focus on what they CAN do, not what they cannot. Every child has strengths — find and build on them. Maintain routines — predictability reduces anxiety. Break tasks into small steps. Use positive reinforcement — praise specific behaviours ("you waited patiently" rather than "good boy"). Communicate with their school regularly. Connect with other parents of children with similar needs — sharing experiences reduces isolation. Take care of your own mental health — caring for a child with additional needs is demanding work. Ask for help when you need it. Your child\'s worth is not measured by their grades or milestones.',
    bodyTa: 'அவர்களால் என்ன செய்ய முடியும் என்பதில் கவனம் செலுத்துங்கள், என்ன செய்ய முடியாது என்பதில் அல்ல. ஒவ்வொரு குழந்தைக்கும் வலிமைகள் உள்ளன — அவற்றைக் கண்டுபிடித்து அதன் மீது கட்டுங்கள். வழக்கங்களை பராமரியுங்கள் — கணிக்கக்கூடிய தன்மை பதற்றத்தை குறைக்கிறது. பணிகளை சிறிய படிகளாக பிரியுங்கள். நேர்மறை வலுவூட்டலை பயன்படுத்துங்கள். பள்ளியுடன் தொடர்ந்து தொடர்பு கொள்ளுங்கள். ஒத்த தேவைகள் கொண்ட குழந்தைகளின் பிற பெற்றோருடன் இணையுங்கள்.',
    tags: ['SEND', 'home support', 'parenting', 'general', 'practical tips'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },

  // === SCHOOL ADVOCACY ===
  {
    id: 'send-school-1',
    titleEn: 'Advocating for Your Child at School',
    titleTa: 'பள்ளியில் உங்கள் குழந்தைக்காக வாதாடுதல்',
    bodyEn: 'Every child has the right to education. If your child has additional needs: 1) Request a meeting with the class teacher and principal. 2) Describe your child\'s strengths and challenges clearly. 3) Ask what support the school can provide (seating near the board, extra time for tests, simplified instructions). 4) Ask if there is a Special Education teacher or resource room. 5) Request regular updates on your child\'s progress. 6) If the school is not responsive, contact the Zonal Education Office. Under Sri Lanka\'s inclusive education policy, schools should make reasonable accommodations. You are your child\'s best advocate — speak up with confidence.',
    bodyTa: 'ஒவ்வொரு குழந்தைக்கும் கல்வி பெறும் உரிமை உண்டு. உங்கள் குழந்தைக்கு கூடுதல் தேவைகள் இருந்தால்: 1) வகுப்பு ஆசிரியர் மற்றும் அதிபருடன் சந்திப்பை கோருங்கள். 2) உங்கள் குழந்தையின் வலிமைகள் மற்றும் சவால்களை தெளிவாக விவரியுங்கள். 3) பள்ளி என்ன ஆதரவை வழங்க முடியும் என்று கேளுங்கள். 4) சிறப்பு கல்வி ஆசிரியர் அல்லது வள அறை உள்ளதா என்று கேளுங்கள். 5) உங்கள் குழந்தையின் முன்னேற்றம் பற்றி வழக்கமான புதுப்பிப்புகளை கோருங்கள்.',
    tags: ['advocacy', 'school', 'rights', 'inclusive education', 'parents'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },

  // === SERVICES & ORGANISATIONS ===
  {
    id: 'send-org-1',
    titleEn: 'Cerebral Palsy Alliance — Sri Lanka',
    titleTa: 'பெருமூளை வாதம் கூட்டமைப்பு — இலங்கை',
    bodyEn: 'Provides physiotherapy, occupational therapy, speech therapy, and family support for children and adults with cerebral palsy. Runs home visit programmes in the Northern and Eastern Provinces. Parent training workshops held quarterly. Equipment (wheelchairs, standing frames) provided based on need assessment. All services free of charge.',
    bodyTa: 'பெருமூளை வாதம் கொண்ட குழந்தைகள் மற்றும் பெரியவர்களுக்கு இயன்முறை சிகிச்சை, தொழில் சிகிச்சை, பேச்சு சிகிச்சை மற்றும் குடும்ப ஆதரவை வழங்குகிறது. வடக்கு மற்றும் கிழக்கு மாகாணங்களில் வீட்டுக்கு வருகை நிரல்களை நடத்துகிறது. காலாண்டுதோறும் பெற்றோர் பயிற்சி பட்டறைகள். தேவை மதிப்பீட்டின் அடிப்படையில் உபகரணங்கள் வழங்கப்படும். அனைத்து சேவைகளும் இலவசம்.',
    tags: ['cerebral palsy', 'physiotherapy', 'disability', 'children', 'equipment'],
    region: 'national',
    contact: {
      phone: '+94 11 269 4132',
      email: 'info@cpasl.org',
      website: 'https://cerebralpalsy.lk',
      address: 'Colombo, Sri Lanka',
    },
    type: 'resource',
  },
  {
    id: 'send-org-2',
    titleEn: 'Jaffna Teaching Hospital — Child Development Clinic',
    titleTa: 'யாழ்ப்பாண போதனா மருத்துவமனை — குழந்தை வளர்ச்சி மருத்துவ நிலையம்',
    bodyEn: 'The paediatric department at Jaffna Teaching Hospital runs a child development clinic for assessment of developmental delays, autism, and learning difficulties. Referral from a GP or MOH recommended but not always required. Ask at the paediatric outpatient department. Audiology and ophthalmology services also available for hearing and vision assessments.',
    bodyTa: 'யாழ்ப்பாண போதனா மருத்துவமனையின் குழந்தை மருத்துவ பிரிவு வளர்ச்சி தாமதங்கள், மன இயல்புத்தன்மை மற்றும் கற்றல் சிரமங்களின் மதிப்பீட்டிற்கான குழந்தை வளர்ச்சி மருத்துவ நிலையத்தை நடத்துகிறது. GP அல்லது MOH-இடமிருந்து பரிந்துரை பரிந்துரைக்கப்படுகிறது ஆனால் எப்போதும் தேவையில்லை.',
    tags: ['hospital', 'child development', 'assessment', 'autism', 'Northern Province'],
    region: 'north',
    contact: {
      phone: '+94 21 222 2261',
      website: 'https://www.health.gov.lk/moh_final/english/hospital.php?spession=Jaffna',
      address: 'Hospital Road, Jaffna',
    },
    type: 'resource',
  },
  {
    id: 'send-org-3',
    titleEn: 'National Council for Persons with Disabilities',
    titleTa: 'குறைபாடுள்ளோருக்கான தேசிய சபை',
    bodyEn: 'The government body responsible for disability rights and services in Sri Lanka. Can provide: disability identity cards (which unlock access to benefits), information about assistive devices, vocational training referrals, and information about your legal rights. Office in Colombo with regional coordinators in each province.',
    bodyTa: 'இலங்கையில் குறைபாடு உரிமைகள் மற்றும் சேவைகளுக்கு பொறுப்பான அரசாங்க அமைப்பு. வழங்க முடியும்: குறைபாடு அடையாள அட்டைகள் (நலன்களுக்கான அணுகலைத் திறக்கும்), உதவிக் கருவிகள் பற்றிய தகவல்கள், தொழிற்பயிற்சி பரிந்துரைகள், உங்கள் சட்ட உரிமைகள் பற்றிய தகவல்கள்.',
    tags: ['disability rights', 'government', 'identity card', 'benefits', 'national'],
    region: 'national',
    contact: {
      phone: '+94 11 218 6080',
      website: 'https://www.socialwelfare.gov.lk',
      address: 'No. 159, Kirulapone Avenue, Colombo 05',
    },
    type: 'resource',
  },
  {
    id: 'send-org-4',
    titleEn: 'Special Education Unit — Zonal Education Office',
    titleTa: 'சிறப்பு கல்வி பிரிவு — வலய கல்வி அலுவலகம்',
    bodyEn: 'Each Zonal Education Office has a Special Education Unit that can advise schools and parents on inclusive education. They can help arrange assessments, coordinate with specialist teachers, and mediate if a school is not providing adequate support. Contact your nearest Zonal Education Office and ask for the Special Education coordinator.',
    bodyTa: 'ஒவ்வொரு வலய கல்வி அலுவலகத்திலும் உள்ளடக்கிய கல்வி பற்றி பள்ளிகள் மற்றும் பெற்றோருக்கு ஆலோசனை வழங்கக்கூடிய சிறப்பு கல்வி பிரிவு உள்ளது. மதிப்பீடுகளை ஏற்பாடு செய்ய, நிபுணர் ஆசிரியர்களுடன் ஒருங்கிணைக்க, பள்ளி போதுமான ஆதரவை வழங்காவிட்டால் மத்தியஸ்தம் செய்ய உதவ முடியும்.',
    tags: ['education', 'government', 'inclusive education', 'schools', 'special education'],
    region: 'all',
    contact: {
      website: 'https://moe.gov.lk',
      phone: '+94 11 278 4811',
    },
    type: 'resource',
  },
];
