import type { ContentItem, PathwayItem } from '@/lib/types';

export const technologyContent: ContentItem[] = [
  {
    id: 'tech-1',
    titleEn: 'Using WhatsApp Safely',
    titleTa: 'WhatsApp-ஐ பாதுகாப்பாக பயன்படுத்துதல்',
    bodyEn: 'WhatsApp is a powerful communication tool. To stay safe: enable two-step verification, never share your verification code with anyone, be cautious of messages from unknown numbers, and do not forward unverified information. Your messages are encrypted, but screenshots can still be shared.',
    bodyTa: 'WhatsApp ஒரு சக்திவாய்ந்த தகவல் தொடர்பு கருவி. பாதுகாப்பாக இருக்க: இரண்டு-படி சரிபார்ப்பை இயக்குங்கள், உங்கள் சரிபார்ப்பு குறியீட்டை யாருடனும் பகிர வேண்டாம், அறியாத எண்களிலிருந்து வரும் செய்திகளில் எச்சரிக்கையாக இருங்கள்.',
    tags: ['WhatsApp', 'safety', 'beginner'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'tech-2',
    titleEn: 'Avoiding Online Scams',
    titleTa: 'ஆன்லைன் மோசடிகளைத் தவிர்த்தல்',
    bodyEn: 'Common scams include fake job offers, lottery wins, and requests for personal information. Never send money to someone you have not met in person. Legitimate organisations will never ask for your password. If something sounds too good to be true, it probably is.',
    bodyTa: 'பொதுவான மோசடிகளில் போலி வேலை வாய்ப்புகள், லாட்டரி வெற்றிகள் மற்றும் தனிப்பட்ட தகவல் கோரிக்கைகள் அடங்கும். நேரில் சந்திக்காத ஒருவருக்கு பணம் அனுப்ப வேண்டாம். சட்டபூர்வ நிறுவனங்கள் ஒருபோதும் உங்கள் கடவுச்சொல்லை கேட்காது.',
    tags: ['scams', 'safety', 'awareness'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'tech-3',
    titleEn: 'Understanding AI — A Simple Guide',
    titleTa: 'AI-ஐ புரிந்துகொள்ளுதல் — எளிய வழிகாட்டி',
    bodyEn: 'AI (Artificial Intelligence) is technology that can learn from data and help with tasks. You might already use AI through voice assistants, autocomplete text, or photo filters. Free AI tools like ChatGPT can help with writing, translating, learning, and answering questions. Always verify AI-generated information and never share personal details with AI tools.',
    bodyTa: 'AI (செயற்கை நுண்ணறிவு) தரவுகளிலிருந்து கற்றுக்கொண்டு பணிகளுக்கு உதவக்கூடிய தொழில்நுட்பம். குரல் உதவியாளர்கள், தானியங்கு உரை நிறைவு, புகைப்பட வடிகட்டிகள் மூலம் நீங்கள் ஏற்கனவே AI-ஐ பயன்படுத்தலாம். ChatGPT போன்ற இலவச AI கருவிகள் எழுத, மொழிபெயர்க்க, கற்க உதவும்.',
    tags: ['AI', 'digital literacy', 'beginner'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'tech-4',
    titleEn: 'Free Digital Tools for Your Phone',
    titleTa: 'உங்கள் தொலைபேசிக்கான இலவச டிஜிட்டல் கருவிகள்',
    bodyEn: 'Useful free tools: Google Sheets (bookkeeping), Canva (design), Google Translate (translation), Khan Academy (learning), WhatsApp Business (customer management), Google Maps (navigation). All available on Android and work on basic smartphones.',
    bodyTa: 'பயனுள்ள இலவச கருவிகள்: Google Sheets (கணக்கு வைத்தல்), Canva (வடிவமைப்பு), Google Translate (மொழிபெயர்ப்பு), Khan Academy (கற்றல்), WhatsApp Business (வாடிக்கையாளர் மேலாண்மை), Google Maps (வழிசெலுத்தல்).',
    tags: ['tools', 'free', 'smartphone'],
    region: 'all',
    type: 'resource',
  },
  {
    id: 'tech-5',
    titleEn: 'Making Money with Your Smartphone',
    titleTa: 'உங்கள் ஸ்மார்ட்ஃபோனில் பணம் சம்பாதித்தல்',
    bodyEn: 'Your smartphone can be a tool for earning income. Options include: freelancing on platforms like Fiverr (translation, data entry, design), selling handmade goods via Facebook Marketplace, tutoring via video calls, or creating Tamil-language content on YouTube. Start small, be consistent, and build your reputation over time.',
    bodyTa: 'உங்கள் ஸ்மார்ட்ஃபோன் வருமானம் ஈட்டும் கருவியாக இருக்கலாம். விருப்பங்களில் அடங்கும்: Fiverr போன்ற தளங்களில் ஃப்ரீலான்சிங் (மொழிபெயர்ப்பு, தரவு உள்ளீடு, வடிவமைப்பு), Facebook Marketplace மூலம் கைவினைப் பொருட்கள் விற்பனை, வீடியோ அழைப்புகள் மூலம் பயிற்சி, YouTube-இல் தமிழ் உள்ளடக்கம் உருவாக்குதல்.',
    tags: ['income', 'freelancing', 'digital work'],
    region: 'all',
    type: 'explainer',
  },
];

export const technologyPathways: PathwayItem[] = [
  {
    id: 'pathway-content-creator',
    titleEn: 'Content Creator',
    titleTa: 'உள்ளடக்க படைப்பாளர்',
    icon: 'video',
    timeToIncomeEn: '2–6 months',
    timeToIncomeTa: '2–6 மாதங்கள்',
    skillLevelEn: 'Beginner',
    skillLevelTa: 'தொடக்கநிலை',
    descriptionEn: 'Create Tamil-language content on YouTube, TikTok, or Instagram. Share knowledge, stories, recipes, music, or educational content. Monetise through ads, sponsorships, and community support.',
    descriptionTa: 'YouTube, TikTok அல்லது Instagram-இல் தமிழ் மொழி உள்ளடக்கத்தை உருவாக்குங்கள். அறிவு, கதைகள், சமையல், இசை அல்லது கல்வி உள்ளடக்கத்தை பகிருங்கள். விளம்பரங்கள், ஸ்பான்சர்ஷிப்கள் மூலம் பணம் சம்பாதியுங்கள்.',
    stepsEn: [
      'Choose a topic you know well and enjoy talking about',
      'Set up a YouTube channel or Instagram account',
      'Record your first video using your phone — it does not need to be perfect',
      'Post consistently (at least once a week)',
      'Engage with your audience in comments',
      'Apply for YouTube monetisation once you reach 1,000 subscribers',
    ],
    stepsTa: [
      'நீங்கள் நன்கு அறிந்த மற்றும் பேச விரும்பும் ஒரு தலைப்பை தேர்வு செய்யுங்கள்',
      'YouTube சேனல் அல்லது Instagram கணக்கை உருவாக்குங்கள்',
      'உங்கள் தொலைபேசியைப் பயன்படுத்தி முதல் வீடியோவைப் பதிவு செய்யுங்கள்',
      'தொடர்ந்து இடுகையிடுங்கள் (வாரத்திற்கு குறைந்தது ஒரு முறை)',
      'கருத்துகளில் உங்கள் பார்வையாளர்களுடன் ஈடுபடுங்கள்',
      '1,000 சந்தாதாரர்களை அடைந்ததும் YouTube நிதியாக்கத்திற்கு விண்ணப்பியுங்கள்',
    ],
    risksEn: [
      'Income is not guaranteed — growth takes time',
      'Online harassment is possible — learn to manage comments',
      'Content moderation rules vary by platform',
    ],
    risksTa: [
      'வருமானம் உத்தரவாதம் இல்லை — வளர்ச்சிக்கு நேரம் தேவை',
      'ஆன்லைன் தொந்தரவு சாத்தியம் — கருத்துகளை நிர்வகிக்க கற்றுக்கொள்ளுங்கள்',
      'உள்ளடக்க மதிப்பாய்வு விதிகள் தளத்திற்கு தளம் மாறுபடும்',
    ],
    resourcesEn: ['YouTube Creator Academy (free)', 'Canva for thumbnails and graphics', 'CapCut for video editing (free)'],
    resourcesTa: ['YouTube Creator Academy (இலவசம்)', 'சிறு படங்கள் மற்றும் வடிவமைப்புக்கு Canva', 'வீடியோ எடிட்டிங்கிற்கு CapCut (இலவசம்)'],
  },
  {
    id: 'pathway-digital-seller',
    titleEn: 'Digital Seller',
    titleTa: 'டிஜிட்டல் விற்பனையாளர்',
    icon: 'store',
    timeToIncomeEn: '1–3 months',
    timeToIncomeTa: '1–3 மாதங்கள்',
    skillLevelEn: 'Beginner',
    skillLevelTa: 'தொடக்கநிலை',
    descriptionEn: 'Sell handmade goods, clothing, food, or local products via Facebook Marketplace, Instagram, or WhatsApp. Use your phone to photograph products, manage orders, and communicate with customers.',
    descriptionTa: 'Facebook Marketplace, Instagram அல்லது WhatsApp மூலம் கைவினைப் பொருட்கள், ஆடைகள், உணவு அல்லது உள்ளூர் பொருட்களை விற்கவும். தயாரிப்புகளை புகைப்படம் எடுக்க, ஆர்டர்களை நிர்வகிக்க, வாடிக்கையாளர்களுடன் தொடர்பு கொள்ள உங்கள் தொலைபேசியைப் பயன்படுத்துங்கள்.',
    stepsEn: [
      'Decide what to sell — start with something you already make or know well',
      'Take clear photos of your products using natural light',
      'Create a Facebook page or Instagram business account',
      'Set fair prices that cover your costs and time',
      'Respond to customers quickly and politely',
    ],
    stepsTa: [
      'என்ன விற்க வேண்டும் என முடிவு செய்யுங்கள் — நீங்கள் ஏற்கனவே செய்யும் அல்லது நன்கு அறிந்த ஒன்றுடன் தொடங்குங்கள்',
      'இயற்கை ஒளியைப் பயன்படுத்தி உங்கள் தயாரிப்புகளின் தெளிவான புகைப்படங்களை எடுங்கள்',
      'Facebook பக்கம் அல்லது Instagram வணிக கணக்கை உருவாக்குங்கள்',
      'உங்கள் செலவுகள் மற்றும் நேரத்தை ஈடுகட்டும் நியாயமான விலைகளை நிர்ணயிங்கள்',
      'வாடிக்கையாளர்களுக்கு விரைவாகவும் கண்ணியமாகவும் பதிலளியுங்கள்',
    ],
    risksEn: [
      'Competition can be high in popular product categories',
      'Delivery logistics can be challenging in rural areas',
      'Payment disputes may occur — keep records of all transactions',
    ],
    risksTa: [
      'பிரபலமான தயாரிப்பு வகைகளில் போட்டி அதிகமாக இருக்கலாம்',
      'கிராமப்புற பகுதிகளில் டெலிவரி சவாலாக இருக்கலாம்',
      'பணம் செலுத்தும் தகராறுகள் ஏற்படலாம் — அனைத்து பரிவர்த்தனைகளின் பதிவுகளை வையுங்கள்',
    ],
    resourcesEn: ['Facebook Business Suite (free)', 'WhatsApp Business (free)', 'Google Sheets for tracking orders'],
    resourcesTa: ['Facebook Business Suite (இலவசம்)', 'WhatsApp Business (இலவசம்)', 'ஆர்டர்களை கண்காணிக்க Google Sheets'],
  },
  {
    id: 'pathway-freelancer',
    titleEn: 'Skilled Freelancer',
    titleTa: 'திறமையான ஃப்ரீலான்சர்',
    icon: 'briefcase',
    timeToIncomeEn: '1–4 months',
    timeToIncomeTa: '1–4 மாதங்கள்',
    skillLevelEn: 'Intermediate',
    skillLevelTa: 'இடைநிலை',
    descriptionEn: 'Offer services like Tamil-English translation, transcription, data entry, or basic graphic design on freelancing platforms. Work from your phone or a shared computer.',
    descriptionTa: 'ஃப்ரீலான்சிங் தளங்களில் தமிழ்-ஆங்கில மொழிபெயர்ப்பு, டிரான்ஸ்கிரிப்ஷன், தரவு உள்ளீடு அல்லது அடிப்படை கிராஃபிக் வடிவமைப்பு போன்ற சேவைகளை வழங்குங்கள்.',
    stepsEn: [
      'Identify your strongest skill (translation, typing, design)',
      'Create a profile on Fiverr or Upwork with a clear description',
      'Start with competitive pricing to build reviews',
      'Deliver high-quality work on time',
      'Gradually increase your rates as you get more reviews',
    ],
    stepsTa: [
      'உங்கள் வலுவான திறனை அடையாளம் காணுங்கள் (மொழிபெயர்ப்பு, தட்டச்சு, வடிவமைப்பு)',
      'Fiverr அல்லது Upwork-இல் தெளிவான விளக்கத்துடன் சுயவிவரத்தை உருவாக்குங்கள்',
      'மதிப்புரைகளை உருவாக்க போட்டி விலையில் தொடங்குங்கள்',
      'உயர் தர வேலையை சரியான நேரத்தில் வழங்குங்கள்',
      'அதிக மதிப்புரைகள் கிடைக்கும்போது படிப்படியாக உங்கள் கட்டணத்தை அதிகரிக்கவும்',
    ],
    risksEn: [
      'Income can be irregular, especially at the beginning',
      'Platform fees reduce your earnings (typically 20%)',
      'Client disputes may occur — maintain professional communication',
    ],
    risksTa: [
      'வருமானம் ஒழுங்கற்றதாக இருக்கலாம், குறிப்பாக ஆரம்பத்தில்',
      'தள கட்டணங்கள் உங்கள் வருமானத்தை குறைக்கும் (பொதுவாக 20%)',
      'வாடிக்கையாளர் தகராறுகள் ஏற்படலாம் — தொழில்முறை தொடர்பை பராமரிக்கவும்',
    ],
    resourcesEn: ['Fiverr (fiverr.com)', 'Upwork (upwork.com)', 'Canva for design work'],
    resourcesTa: ['Fiverr (fiverr.com)', 'Upwork (upwork.com)', 'வடிவமைப்பு வேலைக்கு Canva'],
  },
  {
    id: 'pathway-educator',
    titleEn: 'Community Educator',
    titleTa: 'சமூக கல்வியாளர்',
    icon: 'graduation-cap',
    timeToIncomeEn: '1–2 months',
    timeToIncomeTa: '1–2 மாதங்கள்',
    skillLevelEn: 'Beginner to Intermediate',
    skillLevelTa: 'தொடக்க முதல் இடைநிலை',
    descriptionEn: 'Share your knowledge by tutoring via WhatsApp or video call, running a learning group, or creating educational content. If you know something well — maths, English, cooking, sewing — someone will pay to learn it.',
    descriptionTa: 'WhatsApp அல்லது வீடியோ அழைப்பு மூலம் பயிற்சி, கற்றல் குழுவை நடத்துதல், கல்வி உள்ளடக்கத்தை உருவாக்குதல் ஆகியவை மூலம் உங்கள் அறிவைப் பகிருங்கள். நீங்கள் ஒன்றை நன்கு அறிந்திருந்தால் — கணிதம், ஆங்கிலம், சமையல், தையல் — யாரோ கற்க பணம் செலுத்துவார்கள்.',
    stepsEn: [
      'Choose a subject you are confident teaching',
      'Start with one or two students from your network',
      'Use WhatsApp video call or Google Meet for online sessions',
      'Set a simple schedule and stick to it',
      'Ask happy students to recommend you to others',
    ],
    stepsTa: [
      'நீங்கள் கற்பிக்க நம்பிக்கையான ஒரு பாடத்தை தேர்வு செய்யுங்கள்',
      'உங்கள் தொடர்புகளிலிருந்து ஒன்று அல்லது இரண்டு மாணவர்களுடன் தொடங்குங்கள்',
      'ஆன்லைன் அமர்வுகளுக்கு WhatsApp வீடியோ அழைப்பு அல்லது Google Meet-ஐ பயன்படுத்துங்கள்',
      'எளிய அட்டவணையை அமைத்து அதில் நிலையாக இருங்கள்',
      'மகிழ்ச்சியான மாணவர்களை மற்றவர்களுக்கு பரிந்துரைக்கச் சொல்லுங்கள்',
    ],
    risksEn: [
      'Students may cancel or not pay on time',
      'Internet quality can affect video sessions',
      'You may need to adapt your teaching style for different learners',
    ],
    risksTa: [
      'மாணவர்கள் ரத்து செய்யலாம் அல்லது சரியான நேரத்தில் பணம் செலுத்தாமல் போகலாம்',
      'இணைய தரம் வீடியோ அமர்வுகளை பாதிக்கலாம்',
      'வெவ்வேறு கற்போருக்கு உங்கள் கற்பித்தல் பாணியை மாற்றியமைக்க வேண்டியிருக்கலாம்',
    ],
    resourcesEn: ['WhatsApp (free)', 'Google Meet (free)', 'Google Classroom (free)'],
    resourcesTa: ['WhatsApp (இலவசம்)', 'Google Meet (இலவசம்)', 'Google Classroom (இலவசம்)'],
  },
];
