import type { ContentItem, PathwayItem } from '@/lib/types';

export const technologyContent: ContentItem[] = [
  // === GETTING STARTED ===
  {
    id: 'tech-whatsapp',
    titleEn: 'Using WhatsApp Safely',
    titleTa: 'WhatsApp-ஐ பாதுகாப்பாக பயன்படுத்துதல்',
    bodyEn: 'WhatsApp is the most popular communication tool in Sri Lanka. To stay safe: 1) Enable two-step verification (Settings > Account > Two-step verification). 2) Never share your 6-digit verification code — WhatsApp will never ask for it. 3) Be cautious of messages from unknown numbers, especially those offering jobs, prizes, or asking for money. 4) Do not forward unverified news — check before you share. 5) Block and report numbers that send spam or threats. 6) Review who can see your profile photo and status (Settings > Privacy). Your messages are encrypted end-to-end, but screenshots can still be shared — be careful what you send.',
    bodyTa: 'WhatsApp இலங்கையில் மிகவும் பிரபலமான தகவல் தொடர்பு கருவி. பாதுகாப்பாக இருக்க: 1) இரண்டு-படி சரிபார்ப்பை இயக்குங்கள். 2) உங்கள் 6-இலக்க சரிபார்ப்பு குறியீட்டை பகிர வேண்டாம். 3) அறியாத எண்களிலிருந்து வரும் செய்திகளில் எச்சரிக்கையாக இருங்கள். 4) சரிபார்க்கப்படாத செய்திகளை அனுப்ப வேண்டாம். 5) ஸ்பேம் அல்லது அச்சுறுத்தல்கள் அனுப்பும் எண்களை தடை செய்யுங்கள். 6) உங்கள் சுயவிவர படம் மற்றும் நிலையை யார் பார்க்கலாம் என்பதை மதிப்பாய்வு செய்யுங்கள்.',
    tags: ['WhatsApp', 'safety', 'beginner', 'privacy', 'messaging'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'tech-google-maps',
    titleEn: 'Using Google Maps — Never Get Lost',
    titleTa: 'Google Maps பயன்படுத்துதல் — ஒருபோதும் வழி தவறாதீர்கள்',
    bodyEn: 'Google Maps works well in Sri Lanka, including in the North and East. How to use it: 1) Open Google Maps on your phone. 2) Type where you want to go in the search bar. 3) Tap "Directions" to see the route. 4) Choose driving, walking, or public transport. 5) Tap "Start" for turn-by-turn navigation. Offline tip: before travelling to an area with poor network, download the map for offline use (tap your profile picture > Offline maps > Select your own map). You can also search for nearby services: type "hospital near me", "pharmacy near me", or "bank near me".',
    bodyTa: 'Google Maps இலங்கையில் நன்றாக வேலை செய்கிறது, வடக்கு மற்றும் கிழக்கு உட்பட. பயன்படுத்துவது: 1) தொலைபேசியில் Google Maps திறக்கவும். 2) தேடல் பட்டியில் எங்கு செல்ல வேண்டும் என தட்டச்சு செய்யவும். 3) வழியை பார்க்க "Directions" தட்டவும். 4) வாகனம், நடை அல்லது பொது போக்குவரத்து தேர்வு செய்யவும். ஆஃப்லைன் குறிப்பு: மோசமான நெட்வொர்க் உள்ள பகுதிக்கு பயணிக்கும் முன், ஆஃப்லைன் பயன்பாட்டிற்கு வரைபடத்தை பதிவிறக்கம் செய்யுங்கள்.',
    tags: ['Google Maps', 'navigation', 'beginner', 'offline', 'practical'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'tech-scams',
    titleEn: 'Avoiding Online Scams — Protect Yourself',
    titleTa: 'ஆன்லைன் மோசடிகளைத் தவிர்த்தல் — உங்களைப் பாதுகாத்துக் கொள்ளுங்கள்',
    bodyEn: 'Common scams targeting Sri Lankans: 1) Fake job offers — "work from home, earn $500/day" — if it sounds too good, it is. 2) Lottery/prize messages — you cannot win a contest you never entered. 3) Bank messages asking you to "verify your account" — your bank will never ask for your PIN or password via SMS. 4) Romance scams — strangers online who quickly profess love and then ask for money. 5) Investment scams — "guaranteed 50% returns" — no legitimate investment guarantees returns. Protection: never send money to someone you have not met in person, never share passwords or PINs, verify any offer by calling the organisation directly using a number from their official website, and talk to a trusted person before making financial decisions based on online messages.',
    bodyTa: 'இலங்கையர்களை குறிவைக்கும் பொதுவான மோசடிகள்: 1) போலி வேலை வாய்ப்புகள் — "வீட்டிலிருந்து வேலை, நாளுக்கு $500 சம்பாதியுங்கள்" — மிகவும் நன்றாக தெரிந்தால், அது மோசடி. 2) லாட்டரி/பரிசு செய்திகள் — நீங்கள் நுழையாத போட்டியில் வெற்றி பெற முடியாது. 3) உங்கள் கணக்கை "சரிபார்க்க" கேட்கும் வங்கி செய்திகள் — உங்கள் வங்கி SMS மூலம் PIN அல்லது கடவுச்சொல்லை கேட்காது. 4) காதல் மோசடிகள் — விரைவாக காதலை சொல்லிவிட்டு பணம் கேட்கும் ஆன்லைன் அந்நியர்கள்.',
    tags: ['scams', 'safety', 'awareness', 'fraud', 'protection', 'beginner'],
    region: 'all',
    type: 'guide',
  },
  {
    id: 'tech-data-safety',
    titleEn: 'Protecting Your Personal Data',
    titleTa: 'உங்கள் தனிப்பட்ட தரவைப் பாதுகாத்தல்',
    bodyEn: 'Your phone contains a lot of personal information. Protect it: 1) Set a screen lock (PIN, pattern, or fingerprint). 2) Keep your phone\'s software updated — updates fix security problems. 3) Only download apps from the Google Play Store or Apple App Store. 4) Be careful with app permissions — a flashlight app does not need access to your contacts. 5) Do not use the same password for everything — use different passwords for your email, bank, and social media. 6) Back up your important photos and contacts to Google Drive (free). 7) If your phone is stolen, use "Find My Device" (Google) to lock or erase it remotely.',
    bodyTa: 'உங்கள் தொலைபேசியில் நிறைய தனிப்பட்ட தகவல்கள் உள்ளன. பாதுகாக்கவும்: 1) திரை பூட்டு அமையுங்கள் (PIN, பேட்டர்ன் அல்லது கைரேகை). 2) உங்கள் தொலைபேசியின் மென்பொருளை புதுப்பித்த நிலையில் வையுங்கள். 3) Google Play Store அல்லது Apple App Store-இலிருந்து மட்டுமே செயலிகளை பதிவிறக்கம் செய்யுங்கள். 4) செயலி அனுமதிகளில் கவனமாக இருங்கள். 5) எல்லாவற்றிற்கும் ஒரே கடவுச்சொல்லை பயன்படுத்தாதீர்கள்.',
    tags: ['data safety', 'privacy', 'security', 'passwords', 'beginner'],
    region: 'all',
    type: 'guide',
  },

  // === UNDERSTANDING AI ===
  {
    id: 'tech-ai-basics',
    titleEn: 'Understanding AI — A Simple Guide',
    titleTa: 'AI-ஐ புரிந்துகொள்ளுதல் — எளிய வழிகாட்டி',
    bodyEn: 'AI (Artificial Intelligence) is technology that can learn from data and perform tasks that usually require human thinking. You already use AI every day: voice assistants (Google Assistant, Siri), autocomplete when you type a message, photo filters on Instagram, YouTube video recommendations, and spam filters in your email. Free AI tools you can use: ChatGPT and Google Gemini can help with writing letters, translating between languages, explaining difficult concepts, helping with homework, brainstorming business ideas, and answering questions. Important: AI can make mistakes — always verify important information. Never share personal details (ID numbers, passwords, bank details) with AI tools. AI is a tool to assist you, not replace your own judgement.',
    bodyTa: 'AI (செயற்கை நுண்ணறிவு) தரவுகளிலிருந்து கற்றுக்கொண்டு பொதுவாக மனித சிந்தனை தேவைப்படும் பணிகளை செய்யக்கூடிய தொழில்நுட்பம். நீங்கள் ஏற்கனவே தினமும் AI-ஐ பயன்படுத்துகிறீர்கள்: குரல் உதவியாளர்கள், செய்தி தட்டச்சு செய்யும்போது தானியங்கு நிறைவு, Instagram புகைப்பட வடிகட்டிகள், YouTube வீடியோ பரிந்துரைகள். இலவச AI கருவிகள்: ChatGPT மற்றும் Google Gemini கடிதங்கள் எழுத, மொழிபெயர்க்க, கடினமான கருத்துக்களை விளக்க, வீட்டுப்பாடத்திற்கு உதவ, வணிக யோசனைகளை பிறப்பிக்க உதவும்.',
    tags: ['AI', 'digital literacy', 'beginner', 'ChatGPT', 'Gemini', 'tools'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'tech-ai-tamil',
    titleEn: 'Using AI Tools in Tamil',
    titleTa: 'தமிழில் AI கருவிகளை பயன்படுத்துதல்',
    bodyEn: 'Many AI tools now work well in Tamil. You can: type questions to ChatGPT or Google Gemini in Tamil and get Tamil responses, use Google Translate to translate between Tamil and other languages (also works with photos — point your camera at English text to see Tamil translation), use voice typing in Tamil on your phone (Google Keyboard supports Tamil voice input), and use Google Lens to translate signs, menus, or documents in real time. Tip: if an AI gives a poor Tamil response, try asking in simpler sentences or mixing Tamil and English.',
    bodyTa: 'பல AI கருவிகள் இப்போது தமிழில் நன்றாக வேலை செய்கின்றன. நீங்கள் செய்யலாம்: ChatGPT அல்லது Google Gemini-க்கு தமிழில் கேள்விகளை தட்டச்சு செய்து தமிழ் பதில்களைப் பெறலாம், Google Translate-ஐ தமிழ் மற்றும் பிற மொழிகளுக்கு இடையில் மொழிபெயர்க்க பயன்படுத்தலாம் (புகைப்படங்களுடனும் வேலை செய்யும்), உங்கள் தொலைபேசியில் தமிழில் குரல் தட்டச்சு பயன்படுத்தலாம், Google Lens பயன்படுத்தி அறிவிப்புகள், மெனுக்கள் மொழிபெயர்க்கலாம்.',
    tags: ['AI', 'Tamil', 'Google Translate', 'voice typing', 'practical'],
    region: 'all',
    type: 'explainer',
  },

  // === TOOLS & RESOURCES ===
  {
    id: 'tech-tools',
    titleEn: 'Free Digital Tools for Your Phone',
    titleTa: 'உங்கள் தொலைபேசிக்கான இலவச டிஜிட்டல் கருவிகள்',
    bodyEn: 'Essential free tools that work on basic Android smartphones: **Communication**: WhatsApp, WhatsApp Business (for managing customers). **Money**: Google Sheets (bookkeeping), Google Pay (if available). **Learning**: Khan Academy (Tamil maths and science), YouTube (free courses in Tamil), Duolingo (learn English). **Design**: Canva (create posters, logos, social media posts — free tier is powerful). **Video**: CapCut (free video editing), Google Photos (storage and basic editing). **Translation**: Google Translate (text, voice, and camera translation). **Navigation**: Google Maps (works offline with downloaded maps). **Productivity**: Google Keep (notes and to-do lists), Google Calendar (scheduling). All available on the Google Play Store.',
    bodyTa: 'அடிப்படை Android ஸ்மார்ட்ஃபோன்களில் வேலை செய்யும் அத்தியாவசிய இலவச கருவிகள்: **தொடர்பு**: WhatsApp, WhatsApp Business. **பணம்**: Google Sheets (கணக்கு). **கற்றல்**: Khan Academy (தமிழ் கணிதம் மற்றும் அறிவியல்), YouTube, Duolingo (ஆங்கிலம் கற்க). **வடிவமைப்பு**: Canva (போஸ்டர்கள், லோகோக்கள் உருவாக்க). **வீடியோ**: CapCut (இலவச வீடியோ எடிட்டிங்). **மொழிபெயர்ப்பு**: Google Translate. **வழிசெலுத்தல்**: Google Maps.',
    tags: ['tools', 'free', 'smartphone', 'apps', 'Android', 'essential'],
    region: 'all',
    type: 'resource',
  },
  {
    id: 'tech-earning',
    titleEn: 'Making Money with Your Smartphone',
    titleTa: 'உங்கள் ஸ்மார்ட்ஃபோனில் பணம் சம்பாதித்தல்',
    bodyEn: 'Your smartphone can be a tool for earning income. Realistic options include: freelancing on platforms like Fiverr (translation, data entry, voiceover, design), selling handmade goods via Facebook Marketplace or WhatsApp groups, tutoring via video calls, creating Tamil-language content on YouTube (monetisation after 1,000 subscribers), social media management for local businesses, photography for events and products, and running a small online shop. Start small with something you already know. Be consistent — build your reputation over time. Beware of "make money fast" schemes — if they ask you to pay upfront, they are likely scams.',
    bodyTa: 'உங்கள் ஸ்மார்ட்ஃபோன் வருமானம் ஈட்டும் கருவியாக இருக்கலாம். யதார்த்தமான விருப்பங்கள்: Fiverr போன்ற தளங்களில் ஃப்ரீலான்சிங் (மொழிபெயர்ப்பு, தரவு உள்ளீடு, வாய்ஓவர், வடிவமைப்பு), Facebook Marketplace அல்லது WhatsApp குழுக்கள் மூலம் கைவினைப் பொருட்கள் விற்பனை, வீடியோ அழைப்புகள் மூலம் பயிற்சி, YouTube-இல் தமிழ் உள்ளடக்கம் உருவாக்குதல். நீங்கள் ஏற்கனவே அறிந்த ஒன்றுடன் சிறிதாக தொடங்குங்கள்.',
    tags: ['income', 'freelancing', 'digital work', 'smartphone', 'earning'],
    region: 'all',
    type: 'explainer',
  },
];

export const technologyPathways: PathwayItem[] = [
  {
    id: 'pathway-content-creator',
    titleEn: 'Content Creator',
    titleTa: 'உள்ளடக்க படைப்பாளர்',
    icon: 'video',
    timeToIncomeEn: '2–6 months',
    timeToIncomeTa: '2–6 மாதங்கள்',
    skillLevelEn: 'Beginner',
    skillLevelTa: 'தொடக்கநிலை',
    descriptionEn: 'Create Tamil-language content on YouTube, TikTok, or Instagram. Share knowledge, stories, recipes, music, cultural content, or educational material. Monetise through ads, sponsorships, and community support. Tamil-language content is in growing demand as more Sri Lankans come online.',
    descriptionTa: 'YouTube, TikTok அல்லது Instagram-இல் தமிழ் மொழி உள்ளடக்கத்தை உருவாக்குங்கள். அறிவு, கதைகள், சமையல், இசை, கலாச்சார உள்ளடக்கம் அல்லது கல்வி பொருளை பகிருங்கள். தமிழ் மொழி உள்ளடக்கத்திற்கான தேவை அதிகரித்து வருகிறது.',
    stepsEn: [
      'Choose a topic you know well and enjoy — cooking, farming tips, local history, study help, devotional content',
      'Set up a YouTube channel or Instagram account (free — just needs a Google account)',
      'Record your first video using your phone camera — natural light near a window works well',
      'Edit with CapCut (free app) — add titles in Tamil, trim mistakes, add background music',
      'Post consistently — at least once a week, same day each week if possible',
      'Engage with your audience — reply to every comment in the first few months',
      'Apply for YouTube monetisation at 1,000 subscribers and 4,000 watch hours',
      'Approach local businesses for sponsorship once you have a regular audience',
    ],
    stepsTa: [
      'நீங்கள் நன்கு அறிந்த மற்றும் ரசிக்கும் ஒரு தலைப்பை தேர்வு செய்யுங்கள் — சமையல், விவசாய குறிப்புகள், உள்ளூர் வரலாறு, படிப்பு உதவி',
      'YouTube சேனல் அல்லது Instagram கணக்கை உருவாக்குங்கள் (இலவசம்)',
      'உங்கள் தொலைபேசி கேமரா பயன்படுத்தி முதல் வீடியோவைப் பதிவு செய்யுங்கள்',
      'CapCut (இலவச செயலி) மூலம் எடிட் செய்யுங்கள்',
      'தொடர்ந்து இடுகையிடுங்கள் — வாரத்திற்கு குறைந்தது ஒரு முறை',
      'உங்கள் பார்வையாளர்களுடன் ஈடுபடுங்கள் — முதல் சில மாதங்களில் ஒவ்வொரு கருத்துக்கும் பதிலளியுங்கள்',
      '1,000 சந்தாதாரர்கள் மற்றும் 4,000 பார்வை மணி நேரத்தில் YouTube நிதியாக்கத்திற்கு விண்ணப்பியுங்கள்',
      'வழக்கமான பார்வையாளர்கள் கிடைத்ததும் உள்ளூர் வணிகங்களை ஸ்பான்சர்ஷிப்புக்கு அணுகுங்கள்',
    ],
    risksEn: [
      'Income is not guaranteed in the first 6–12 months — treat it as a side project initially',
      'Online harassment is possible — learn to block, report, and not engage with trolls',
      'Content moderation rules vary by platform — YouTube may demonetise certain topics',
      'Consistent content creation requires time and energy — start with a sustainable pace',
    ],
    risksTa: [
      'முதல் 6–12 மாதங்களில் வருமானம் உத்தரவாதம் இல்லை — ஆரம்பத்தில் பக்க திட்டமாக கருதுங்கள்',
      'ஆன்லைன் தொந்தரவு சாத்தியம் — தடை செய்ய, புகாரளிக்க கற்றுக்கொள்ளுங்கள்',
      'உள்ளடக்க மதிப்பாய்வு விதிகள் தளத்திற்கு தளம் மாறுபடும்',
      'தொடர்ந்த உள்ளடக்க உருவாக்கத்திற்கு நேரமும் ஆற்றலும் தேவை',
    ],
    resourcesEn: ['YouTube Creator Academy (free online course)', 'Canva — free thumbnail and graphics maker', 'CapCut — free video editor for phone', 'VN Video Editor — alternative free editor'],
    resourcesTa: ['YouTube Creator Academy (இலவச ஆன்லைன் படிப்பு)', 'Canva — இலவச சிறு படம் மற்றும் வடிவமைப்பு', 'CapCut — தொலைபேசிக்கான இலவச வீடியோ எடிட்டர்', 'VN Video Editor — மாற்று இலவச எடிட்டர்'],
  },
  {
    id: 'pathway-digital-seller',
    titleEn: 'Digital Seller',
    titleTa: 'டிஜிட்டல் விற்பனையாளர்',
    icon: 'store',
    timeToIncomeEn: '1–3 months',
    timeToIncomeTa: '1–3 மாதங்கள்',
    skillLevelEn: 'Beginner',
    skillLevelTa: 'தொடக்கநிலை',
    descriptionEn: 'Sell handmade goods, clothing, food products, or local crafts via Facebook Marketplace, Instagram, or WhatsApp Business. Use your phone to photograph products, manage orders, and communicate with customers. Particularly strong for: traditional crafts (palmyra products, handloom textiles), home-cooked food, and locally grown produce.',
    descriptionTa: 'Facebook Marketplace, Instagram அல்லது WhatsApp Business மூலம் கைவினைப் பொருட்கள், ஆடைகள், உணவு தயாரிப்புகள் அல்லது உள்ளூர் கைவினைகளை விற்கவும். குறிப்பாக வலுவானது: பாரம்பரிய கைவினைகள் (பனை பொருட்கள், கைத்தறி ஜவுளிகள்), வீட்டில் சமைத்த உணவு, உள்ளூரில் பயிரிடப்பட்ட விளைபொருட்கள்.',
    stepsEn: [
      'Decide what to sell — start with something you already make well or can source locally',
      'Take clear, well-lit photos using natural daylight (near a window, plain background)',
      'Set up a Facebook Business Page or WhatsApp Business profile — both are free',
      'Write clear descriptions in Tamil and English: what it is, size/weight, price, delivery options',
      'Set prices that cover materials + your time + delivery costs + a margin for profit',
      'Respond to customer messages within a few hours — fast replies build trust',
      'Start with local delivery (personal drop-off or local courier) before expanding',
      'Ask satisfied customers to leave reviews and share your page with friends',
    ],
    stepsTa: [
      'என்ன விற்க வேண்டும் என முடிவு செய்யுங்கள் — நீங்கள் ஏற்கனவே நன்றாக செய்யும் அல்லது உள்ளூரில் பெறக்கூடிய ஒன்றுடன் தொடங்குங்கள்',
      'இயற்கை பகல் வெளிச்சத்தில் தெளிவான, நன்கு ஒளிரும் புகைப்படங்களை எடுங்கள்',
      'Facebook Business பக்கம் அல்லது WhatsApp Business சுயவிவரத்தை அமையுங்கள் — இரண்டும் இலவசம்',
      'தமிழிலும் ஆங்கிலத்திலும் தெளிவான விளக்கங்களை எழுதுங்கள்',
      'பொருட்கள் + உங்கள் நேரம் + டெலிவரி செலவுகள் + லாப விளிம்பை உள்ளடக்கும் விலைகளை நிர்ணயிக்கவும்',
      'வாடிக்கையாளர் செய்திகளுக்கு சில மணி நேரத்திற்குள் பதிலளியுங்கள்',
      'விரிவாக்கும் முன் உள்ளூர் டெலிவரியுடன் தொடங்குங்கள்',
      'திருப்தியான வாடிக்கையாளர்களை மதிப்புரைகள் எழுதவும் பக்கத்தை பகிரவும் கேளுங்கள்',
    ],
    risksEn: [
      'Competition can be high — differentiate through quality, story, and customer service',
      'Delivery logistics outside major towns can be challenging — plan delivery areas carefully',
      'Payment disputes may occur — keep screenshots of all orders and conversations',
      'Seasonal demand fluctuations — some products sell better at certain times of year',
    ],
    risksTa: [
      'போட்டி அதிகமாக இருக்கலாம் — தரம், கதை, வாடிக்கையாளர் சேவை மூலம் வேறுபடுத்துங்கள்',
      'முக்கிய நகரங்களுக்கு வெளியே டெலிவரி சவாலாக இருக்கலாம்',
      'பணம் செலுத்தும் தகராறுகள் ஏற்படலாம் — அனைத்து ஆர்டர்கள் மற்றும் உரையாடல்களின் ஸ்கிரீன்ஷாட்களை வையுங்கள்',
      'பருவகால தேவை ஏற்ற இறக்கங்கள் — சில பொருட்கள் சில நேரங்களில் நன்றாக விற்கப்படும்',
    ],
    resourcesEn: ['Facebook Business Suite (free)', 'WhatsApp Business (free)', 'Canva for product graphics (free)', 'Google Sheets for tracking orders and finances'],
    resourcesTa: ['Facebook Business Suite (இலவசம்)', 'WhatsApp Business (இலவசம்)', 'தயாரிப்பு வடிவமைப்புக்கு Canva (இலவசம்)', 'ஆர்டர்கள் மற்றும் நிதி கண்காணிக்க Google Sheets'],
  },
  {
    id: 'pathway-freelancer',
    titleEn: 'Skilled Freelancer',
    titleTa: 'திறமையான ஃப்ரீலான்சர்',
    icon: 'briefcase',
    timeToIncomeEn: '1–4 months',
    timeToIncomeTa: '1–4 மாதங்கள்',
    skillLevelEn: 'Intermediate',
    skillLevelTa: 'இடைநிலை',
    descriptionEn: 'Offer services like Tamil-English translation, transcription, data entry, voiceover, or basic graphic design on international freelancing platforms. Tamil-English bilingual skills are in demand globally. Work from your phone or a shared computer at a library or internet cafe.',
    descriptionTa: 'சர்வதேச ஃப்ரீலான்சிங் தளங்களில் தமிழ்-ஆங்கில மொழிபெயர்ப்பு, டிரான்ஸ்கிரிப்ஷன், தரவு உள்ளீடு, வாய்ஓவர் அல்லது அடிப்படை கிராஃபிக் வடிவமைப்பு போன்ற சேவைகளை வழங்குங்கள். தமிழ்-ஆங்கில இருமொழி திறன்கள் உலகளவில் தேவைப்படுகின்றன.',
    stepsEn: [
      'Identify your strongest marketable skill — translation, typing speed, design, voice quality',
      'Create profiles on Fiverr and Upwork with a clear photo, description of your skills, and samples of your work',
      'Start with competitive pricing to build your first 5–10 reviews — reviews are everything on these platforms',
      'Deliver high-quality work on time, every time — your reputation is your business',
      'Communicate professionally — respond to messages quickly, ask clarifying questions upfront',
      'Gradually increase your rates as you accumulate positive reviews (after 10+ reviews)',
      'Specialise in a niche — "Tamil legal document translation" pays more than "general translation"',
    ],
    stepsTa: [
      'உங்கள் வலுவான சந்தைப்படுத்தக்கூடிய திறனை அடையாளம் காணுங்கள்',
      'Fiverr மற்றும் Upwork-இல் தெளிவான புகைப்படம், திறன் விளக்கம், வேலை மாதிரிகளுடன் சுயவிவரங்களை உருவாக்குங்கள்',
      'முதல் 5–10 மதிப்புரைகளை உருவாக்க போட்டி விலையில் தொடங்குங்கள்',
      'உயர் தர வேலையை சரியான நேரத்தில், ஒவ்வொரு முறையும் வழங்குங்கள்',
      'தொழில்முறையாக தொடர்பு கொள்ளுங்கள் — செய்திகளுக்கு விரைவாக பதிலளியுங்கள்',
      'நேர்மறை மதிப்புரைகள் குவியும்போது படிப்படியாக கட்டணத்தை அதிகரிக்கவும்',
      'ஒரு நிச்சில் நிபுணத்துவம் பெறுங்கள் — "தமிழ் சட்ட ஆவண மொழிபெயர்ப்பு" "பொது மொழிபெயர்ப்பை" விட அதிகம் செலுத்தும்',
    ],
    risksEn: [
      'Income is irregular at first — expect quiet periods, especially in months 1–3',
      'Platform fees reduce earnings by 20% (Fiverr) or 10–20% (Upwork)',
      'Client disputes happen — always keep written records of agreements and deliverables',
      'You need reliable internet access — plan for backup options if your connection is unstable',
    ],
    risksTa: [
      'ஆரம்பத்தில் வருமானம் ஒழுங்கற்றது — அமைதியான காலங்களை எதிர்பாருங்கள்',
      'தள கட்டணங்கள் வருமானத்தை 20% (Fiverr) அல்லது 10–20% (Upwork) குறைக்கும்',
      'வாடிக்கையாளர் தகராறுகள் நடக்கும் — ஒப்பந்தங்களின் எழுத்து பதிவுகளை எப்போதும் வையுங்கள்',
      'நம்பகமான இணைய அணுகல் தேவை — உங்கள் இணைப்பு நிலையற்றதாக இருந்தால் காப்பு விருப்பங்களை திட்டமிடுங்கள்',
    ],
    resourcesEn: ['Fiverr (fiverr.com) — best for beginners', 'Upwork (upwork.com) — better for longer projects', 'Canva for design work (free tier)', 'Google Docs for writing and collaboration'],
    resourcesTa: ['Fiverr (fiverr.com) — தொடக்கநிலையாளர்களுக்கு சிறந்தது', 'Upwork (upwork.com) — நீண்ட திட்டங்களுக்கு சிறந்தது', 'வடிவமைப்பு வேலைக்கு Canva (இலவசம்)', 'எழுதுவதற்கும் ஒத்துழைப்புக்கும் Google Docs'],
  },
  {
    id: 'pathway-educator',
    titleEn: 'Community Educator',
    titleTa: 'சமூக கல்வியாளர்',
    icon: 'graduation-cap',
    timeToIncomeEn: '1–2 months',
    timeToIncomeTa: '1–2 மாதங்கள்',
    skillLevelEn: 'Beginner to Intermediate',
    skillLevelTa: 'தொடக்க முதல் இடைநிலை',
    descriptionEn: 'Share your knowledge by tutoring via WhatsApp or video call, running a learning group, or creating educational content. If you know something well — maths, English, Tamil literature, cooking, sewing, agriculture, fishing techniques — someone will pay to learn it. This is one of the quickest paths to income because you are selling your existing expertise.',
    descriptionTa: 'WhatsApp அல்லது வீடியோ அழைப்பு மூலம் பயிற்சி, கற்றல் குழுவை நடத்துதல், கல்வி உள்ளடக்கத்தை உருவாக்குதல் ஆகியவை மூலம் உங்கள் அறிவைப் பகிருங்கள். நீங்கள் ஒன்றை நன்கு அறிந்திருந்தால் — கணிதம், ஆங்கிலம், தமிழ் இலக்கியம், சமையல், தையல், விவசாயம் — யாரோ கற்க பணம் செலுத்துவார்கள்.',
    stepsEn: [
      'Choose a subject you are confident teaching — start with what people already ask you about',
      'Start with 1–2 students from your network (family, friends, neighbours)',
      'Set clear expectations: schedule (e.g., Tuesday and Thursday 5–6pm), fees, what you will cover',
      'Use WhatsApp video call or Google Meet — both free and work on basic smartphones',
      'Prepare simple lesson notes or share materials via WhatsApp (photos of notes, voice messages explaining concepts)',
      'Ask happy students to recommend you — word of mouth is your best marketing',
      'Consider group sessions (3–5 students at once) to earn more per hour',
      'Create a WhatsApp group for your students to share resources and ask questions between sessions',
    ],
    stepsTa: [
      'நீங்கள் கற்பிக்க நம்பிக்கையான ஒரு பாடத்தை தேர்வு செய்யுங்கள்',
      'உங்கள் தொடர்புகளிலிருந்து 1–2 மாணவர்களுடன் தொடங்குங்கள்',
      'தெளிவான எதிர்பார்ப்புகளை அமையுங்கள்: அட்டவணை, கட்டணம், என்ன உள்ளடக்கப்படும்',
      'WhatsApp வீடியோ அழைப்பு அல்லது Google Meet பயன்படுத்துங்கள் — இரண்டும் இலவசம்',
      'எளிய பாட குறிப்புகளை தயாரியுங்கள் அல்லது WhatsApp மூலம் பொருட்களை பகிருங்கள்',
      'மகிழ்ச்சியான மாணவர்களை உங்களை பரிந்துரைக்க கேளுங்கள்',
      'மணிக்கு அதிகம் சம்பாதிக்க குழு அமர்வுகளை (3–5 மாணவர்கள்) பரிசீலியுங்கள்',
      'அமர்வுகளுக்கு இடையில் வளங்களை பகிர உங்கள் மாணவர்களுக்கு WhatsApp குழு உருவாக்குங்கள்',
    ],
    risksEn: [
      'Students may cancel last minute — consider a cancellation policy (e.g., 24-hour notice)',
      'Internet quality can affect video sessions — have a backup plan (voice call, rescheduling)',
      'You may need to adapt your teaching for different learning styles and paces',
      'Setting boundaries is important — students may message at all hours asking for help',
    ],
    risksTa: [
      'மாணவர்கள் கடைசி நிமிடத்தில் ரத்து செய்யலாம் — ரத்து கொள்கையை பரிசீலியுங்கள்',
      'இணைய தரம் வீடியோ அமர்வுகளை பாதிக்கலாம் — காப்பு திட்டம் வையுங்கள்',
      'வெவ்வேறு கற்றல் பாணிகளுக்கு உங்கள் கற்பித்தலை மாற்றியமைக்க வேண்டியிருக்கலாம்',
      'எல்லைகளை அமைப்பது முக்கியம் — மாணவர்கள் எல்லா நேரத்திலும் உதவி கேட்கலாம்',
    ],
    resourcesEn: ['WhatsApp (free)', 'Google Meet (free, up to 60 minutes)', 'Google Classroom (free, for organising courses)', 'Canva for creating lesson materials (free)'],
    resourcesTa: ['WhatsApp (இலவசம்)', 'Google Meet (இலவசம், 60 நிமிடங்கள் வரை)', 'Google Classroom (இலவசம், படிப்புகளை ஒழுங்கமைக்க)', 'பாட பொருட்கள் உருவாக்க Canva (இலவசம்)'],
  },
];
