import type { ContentItem } from '@/lib/types';

export const wellbeingContent: ContentItem[] = [
  // === CRISIS & EMERGENCY ===
  {
    id: 'wb-crisis-1',
    titleEn: 'Sumithrayo — 24/7 Crisis Support Line',
    titleTa: 'சுமித்ரயோ — 24/7 நெருக்கடி ஆதரவு எண்',
    bodyEn: 'If you or someone you know is in crisis, call Sumithrayo. They provide confidential emotional support for anyone feeling distressed, overwhelmed, or suicidal. The line is open 24 hours, 7 days a week. You do not need to give your name. Calls are free from landlines. Available in Sinhala, Tamil, and English.',
    bodyTa: 'நீங்கள் அல்லது நீங்கள் அறிந்த யாரேனும் நெருக்கடியில் இருந்தால், சுமித்ரயோவை அழையுங்கள். துன்பம், அதிகப்படியான அழுத்தம் அல்லது தற்கொலை எண்ணம் கொண்ட எவருக்கும் ரகசியமான உணர்வு ஆதரவை வழங்குகிறார்கள். 24 மணி நேரமும், வாரம் 7 நாட்களும் திறந்திருக்கும். உங்கள் பெயரை கொடுக்க வேண்டியதில்லை. நிலத்தொலைபேசிகளிலிருந்து அழைப்புகள் இலவசம்.',
    tags: ['crisis', 'hotline', '24/7', 'suicide prevention', 'emergency'],
    region: 'national',
    contact: {
      phone: '+94 11 268 2535',
      website: 'https://sumithrayo.org',
      address: '60/7 Horton Place, Colombo 07',
    },
    type: 'resource',
  },
  {
    id: 'wb-crisis-2',
    titleEn: 'National Mental Health Helpline — 1926',
    titleTa: 'தேசிய மனநல உதவி எண் — 1926',
    bodyEn: 'Dial 1926 for the government mental health helpline operated by the Ministry of Health. Available during office hours (8am–4pm, Monday–Friday). Provides referrals to government mental health services, counselling, and information about treatment options. Tamil-speaking counsellors available.',
    bodyTa: 'சுகாதார அமைச்சகத்தால் இயக்கப்படும் அரசாங்க மனநல உதவி எண்ணுக்கு 1926 என்று டயல் செய்யுங்கள். அலுவலக நேரங்களில் கிடைக்கும் (காலை 8–மாலை 4, திங்கள்–வெள்ளி). அரசாங்க மனநல சேவைகள், ஆலோசனை மற்றும் சிகிச்சை விருப்பங்கள் பற்றிய தகவல்களுக்கு பரிந்துரைகளை வழங்குகிறது.',
    tags: ['crisis', 'hotline', 'government', 'mental health'],
    region: 'national',
    contact: {
      phone: '1926',
      website: 'https://www.health.gov.lk',
    },
    type: 'resource',
  },
  {
    id: 'wb-crisis-3',
    titleEn: 'CCC Line — Women and Children',
    titleTa: 'CCC எண் — பெண்கள் மற்றும் குழந்தைகள்',
    bodyEn: 'The Child and Women Crisis Centre (CCC) helpline provides support for women and children experiencing domestic violence, abuse, or exploitation. Call 1938. Operated by the National Child Protection Authority. Confidential and available in Tamil, Sinhala, and English.',
    bodyTa: 'குழந்தை மற்றும் பெண்கள் நெருக்கடி மையம் (CCC) உதவி எண் வீட்டு வன்முறை, துஷ்பிரயோகம் அல்லது சுரண்டலை அனுபவிக்கும் பெண்கள் மற்றும் குழந்தைகளுக்கு ஆதரவை வழங்குகிறது. 1938 என்று அழையுங்கள். தேசிய குழந்தை பாதுகாப்பு ஆணையத்தால் இயக்கப்படுகிறது. ரகசியமானது.',
    tags: ['crisis', 'women', 'children', 'domestic violence', 'hotline'],
    region: 'national',
    contact: {
      phone: '1938',
      website: 'https://childprotection.gov.lk',
    },
    type: 'resource',
  },

  // === ORGANISATIONS & SERVICES ===
  {
    id: 'wb-org-1',
    titleEn: 'Shanthiham — Psychosocial Support (Jaffna)',
    titleTa: 'சாந்தியம் — உளவியல் சமூக ஆதரவு (யாழ்ப்பாணம்)',
    bodyEn: 'Shanthiham is the leading psychosocial support organisation in the Northern Province. Services include individual counselling, group therapy, community-based support programmes, trauma recovery workshops, and training for community health workers. They work in Tamil and serve all districts of the Northern Province. Walk-ins welcome at the Jaffna office. No referral needed for initial consultation.',
    bodyTa: 'சாந்தியம் வடக்கு மாகாணத்தின் முன்னணி உளவியல் சமூக ஆதரவு நிறுவனம். தனிப்பட்ட ஆலோசனை, குழு சிகிச்சை, சமூக அடிப்படையிலான ஆதரவு திட்டங்கள், அதிர்ச்சி மீட்சி பட்டறைகள், சமூக சுகாதார ஊழியர்களுக்கான பயிற்சி ஆகியவை சேவைகளில் அடங்கும். தமிழில் செயல்படுகிறார்கள், வடக்கு மாகாணத்தின் அனைத்து மாவட்டங்களுக்கும் சேவை செய்கிறார்கள். யாழ்ப்பாண அலுவலகத்தில் நேரடியாக வரலாம். ஆரம்ப ஆலோசனைக்கு பரிந்துரை தேவையில்லை.',
    tags: ['mental health', 'counselling', 'trauma', 'Northern Province', 'Tamil'],
    region: 'north',
    contact: {
      phone: '+94 21 222 7865',
      email: 'info@shanthiham.org',
      website: 'https://shanthiham.org',
      address: 'Nallur, Jaffna',
    },
    type: 'resource',
  },
  {
    id: 'wb-org-2',
    titleEn: 'Family Rehabilitation Centre (FRC)',
    titleTa: 'குடும்ப புனர்வாழ்வு மையம் (FRC)',
    bodyEn: 'FRC provides psychosocial support, counselling, and rehabilitation services to survivors of torture, conflict-related trauma, and their families. Operates in the Northern and Eastern Provinces. Services include individual therapy, family counselling, livelihood support, and legal assistance. All services in Tamil. Referrals from community workers accepted.',
    bodyTa: 'FRC சித்திரவதை, மோதல் தொடர்பான அதிர்ச்சி பாதிக்கப்பட்டவர்கள் மற்றும் அவர்களது குடும்பங்களுக்கு உளவியல் சமூக ஆதரவு, ஆலோசனை மற்றும் புனர்வாழ்வு சேவைகளை வழங்குகிறது. வடக்கு மற்றும் கிழக்கு மாகாணங்களில் செயல்படுகிறது. தனிப்பட்ட சிகிச்சை, குடும்ப ஆலோசனை, வாழ்வாதார ஆதரவு, சட்ட உதவி ஆகியவை சேவைகளில் அடங்கும்.',
    tags: ['mental health', 'trauma', 'torture survivors', 'rehabilitation', 'legal'],
    region: 'north',
    contact: {
      phone: '+94 21 222 5494',
      email: 'frcjaffna@gmail.com',
      website: 'https://frcsl.org',
      address: 'Jaffna, Northern Province',
    },
    type: 'resource',
  },
  {
    id: 'wb-org-3',
    titleEn: 'Batticaloa Psychosocial Support Centre',
    titleTa: 'மட்டக்களப்பு உளவியல் சமூக ஆதரவு மையம்',
    bodyEn: 'Community-based psychosocial support in the Eastern Province. Provides counselling in Tamil for individuals, couples, and families. Specialises in grief support, post-conflict adjustment, and supporting families of the missing and disappeared. Also runs women\'s support groups and children\'s therapy programmes. No fees charged.',
    bodyTa: 'கிழக்கு மாகாணத்தில் சமூக அடிப்படையிலான உளவியல் சமூக ஆதரவு. தனிநபர்கள், தம்பதிகள் மற்றும் குடும்பங்களுக்கு தமிழில் ஆலோசனை வழங்குகிறது. துக்க ஆதரவு, மோதலுக்குப் பிந்தைய சரிசெய்தல், காணாமல் போனவர்களின் குடும்பங்களுக்கு ஆதரவு ஆகியவற்றில் நிபுணத்துவம் பெற்றது. பெண்கள் ஆதரவு குழுக்கள் மற்றும் குழந்தை சிகிச்சை திட்டங்களையும் நடத்துகிறது. கட்டணம் இல்லை.',
    tags: ['mental health', 'counselling', 'Eastern Province', 'grief', 'families of missing'],
    region: 'east',
    contact: {
      phone: '+94 65 222 4781',
      website: 'https://www.health.gov.lk',
      address: 'Batticaloa',
    },
    type: 'resource',
  },
  {
    id: 'wb-org-4',
    titleEn: 'National Institute of Mental Health (NIMH)',
    titleTa: 'தேசிய மனநல நிறுவனம் (NIMH)',
    bodyEn: 'Sri Lanka\'s primary psychiatric hospital providing inpatient treatment, outpatient clinics, and community mental health services. Referrals from regional hospitals or MOH offices. Tamil-speaking psychiatrists available. For severe mental health conditions requiring specialist care. Nearest to Northern/Eastern residents via referral from Jaffna or Batticaloa Teaching Hospitals.',
    bodyTa: 'இலங்கையின் முதன்மை மனநல மருத்துவமனை — உள்நோயாளி சிகிச்சை, வெளிநோயாளி மருத்துவமனைகள், சமூக மனநல சேவைகள் வழங்குகிறது. பிராந்திய மருத்துவமனைகள் அல்லது MOH அலுவலகங்களிலிருந்து பரிந்துரைகள். தமிழ் பேசும் மனநல மருத்துவர்கள் கிடைக்கும். நிபுணர் பராமரிப்பு தேவைப்படும் கடுமையான மனநல நிலைகளுக்கு.',
    tags: ['mental health', 'hospital', 'psychiatry', 'inpatient', 'national'],
    region: 'national',
    contact: {
      phone: '+94 11 257 8234',
      website: 'https://www.health.gov.lk',
      address: 'Angoda, Colombo',
    },
    type: 'resource',
  },
  {
    id: 'wb-org-5',
    titleEn: 'Viluthu Centre for Human Resource Development',
    titleTa: 'விலுத்து மனித வள மேம்பாட்டு மையம்',
    bodyEn: 'Viluthu works with war-affected communities in the North and East, focusing on women\'s wellbeing, community organising, and psychosocial support. They run women\'s circles, peer support training, and community dialogue programmes. Strong Tamil-language presence. They also support families of the forcibly disappeared through group therapy and advocacy.',
    bodyTa: 'விலுத்து வடக்கு மற்றும் கிழக்கில் போரால் பாதிக்கப்பட்ட சமூகங்களுடன் பணியாற்றுகிறது — பெண்கள் நல்வாழ்வு, சமூக ஒழுங்கமைப்பு, உளவியல் சமூக ஆதரவு ஆகியவற்றில் கவனம் செலுத்துகிறது. பெண்கள் வட்டங்கள், சக ஆதரவு பயிற்சி, சமூக உரையாடல் திட்டங்களை நடத்துகிறது. வலுவான தமிழ் மொழி இருப்பு. வலுக்கட்டாயமாக காணாமல் போனவர்களின் குடும்பங்களுக்கு குழு சிகிச்சை மற்றும் வாதாடல் மூலம் ஆதரவு.',
    tags: ['women', 'community', 'psychosocial', 'disappeared families', 'Northern Province'],
    region: 'north',
    contact: {
      phone: '+94 21 222 3876',
      email: 'info@viluthu.org',
      website: 'https://viluthu.org',
      address: 'Jaffna, Northern Province',
    },
    type: 'resource',
  },

  // === GUIDES (TRAINER RESOURCES) ===
  {
    id: 'wb-guide-1',
    titleEn: 'Peer Wellbeing Support Guide',
    titleTa: 'சக நல்வாழ்வு ஆதரவு வழிகாட்டி',
    bodyEn: 'A comprehensive guide for community members on how to support someone in emotional distress. Covers active listening, what to say and what not to say, recognising signs of crisis, when to escalate to professional services, and how to take care of yourself as a supporter. Designed for use by community health workers, religious leaders, teachers, and any community member who wants to help.',
    bodyTa: 'உணர்வுப்பூர்வ மன உளைச்சலில் உள்ள ஒருவரை எப்படி ஆதரிப்பது என்பது பற்றிய சமூக உறுப்பினர்களுக்கான விரிவான வழிகாட்டி. செயலில் கேட்பது, என்ன சொல்ல வேண்டும் என்ன சொல்லக்கூடாது, நெருக்கடி அறிகுறிகளை அறிதல், தொழில்முறை சேவைகளுக்கு எப்போது அனுப்ப வேண்டும், ஆதரவாளராக உங்களை எப்படி பராமரிப்பது என்பதை உள்ளடக்கியது.',
    tags: ['peer support', 'training', 'guide', 'community health', 'active listening'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'wb-guide-2',
    titleEn: 'Running a Community Wellbeing Circle',
    titleTa: 'சமூக நல்வாழ்வு வட்டத்தை நடத்துதல்',
    bodyEn: 'A practical guide for facilitating a weekly or fortnightly community wellbeing circle. A wellbeing circle is a safe space where 5–12 community members meet to share, listen, and support each other. No professional training needed — just the willingness to hold space. Includes: how to invite people, setting ground rules (confidentiality, no judgement, equal speaking time), opening and closing rituals, suggested discussion topics, and what to do if someone shares something concerning.',
    bodyTa: 'வாராந்திர அல்லது இரு வாரத்திற்கு ஒரு முறை சமூக நல்வாழ்வு வட்டத்தை வசதியாக்குவதற்கான நடைமுறை வழிகாட்டி. நல்வாழ்வு வட்டம் 5–12 சமூக உறுப்பினர்கள் பகிர்ந்து, கேட்டு, ஒருவருக்கொருவர் ஆதரிக்க சந்திக்கும் பாதுகாப்பான இடம். தொழில்முறை பயிற்சி தேவையில்லை — இடத்தை நிலைநிறுத்தும் விருப்பம் மட்டுமே தேவை. எப்படி அழைப்பது, அடிப்படை விதிகளை அமைப்பது, தொடக்க மற்றும் நிறைவு சடங்குகள், பரிந்துரைக்கப்பட்ட விவாத தலைப்புகள் உள்ளிட்டவை.',
    tags: ['peer support', 'training', 'facilitation', 'community circles', 'group work'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'wb-guide-3',
    titleEn: 'Supporting Grief and Loss in Community',
    titleTa: 'சமூகத்தில் துக்கம் மற்றும் இழப்பை ஆதரித்தல்',
    bodyEn: 'Many Tamil families carry the weight of unresolved grief — from war, displacement, the tsunami, or the loss of loved ones who remain missing. This guide helps community supporters understand complicated grief, how it manifests differently across ages, and how to be present for someone in pain without trying to fix them. Includes: Tamil cultural approaches to mourning, when grief becomes a health concern, supporting children who have lost parents, and supporting families of the disappeared.',
    bodyTa: 'பல தமிழ் குடும்பங்கள் தீர்க்கப்படாத துக்கத்தின் சுமையை சுமக்கின்றன — போர், இடப்பெயர்வு, சுனாமி, அல்லது காணாமல் போன அன்பானவர்களின் இழப்பு. இந்த வழிகாட்டி சிக்கலான துக்கத்தைப் புரிந்துகொள்ள, வயது வாரியாக எவ்வாறு வெவ்வேறு வடிவங்களில் வெளிப்படுகிறது, சரிசெய்ய முயற்சிக்காமல் வலியில் உள்ள ஒருவருக்கு எவ்வாறு உடனிருப்பது என்பதை சமூக ஆதரவாளர்களுக்கு உதவுகிறது.',
    tags: ['grief', 'loss', 'missing persons', 'training', 'mourning', 'children'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'wb-guide-4',
    titleEn: 'Recognising Mental Health Warning Signs',
    titleTa: 'மனநல எச்சரிக்கை அறிகுறிகளை அறிதல்',
    bodyEn: 'How to recognise when someone in your community may need mental health support. Common signs: withdrawing from family and friends, changes in sleep or appetite, increased use of alcohol or substances, talking about hopelessness or being a burden, giving away possessions, sudden calmness after a period of depression, or difficulty performing daily tasks. What to do: approach with care, express concern without judgement, listen, and offer to help connect them to services. Never leave someone alone if you believe they may harm themselves.',
    bodyTa: 'உங்கள் சமூகத்தில் யாருக்காவது மனநல ஆதரவு தேவைப்படலாம் என்பதை எப்படி அறிவது. பொதுவான அறிகுறிகள்: குடும்பம் மற்றும் நண்பர்களிடமிருந்து விலகுதல், தூக்கம் அல்லது பசியில் மாற்றங்கள், மது அல்லது போதைப்பொருள் பயன்பாடு அதிகரிப்பு, நம்பிக்கையின்மை பற்றி பேசுதல், உடைமைகளை கொடுத்தல், மனச்சோர்வுக்குப் பிறகு திடீர் அமைதி, அன்றாட பணிகளை செய்வதில் சிரமம். என்ன செய்வது: கவனத்துடன் அணுகுங்கள், தீர்ப்பு இல்லாமல் கவலையை வெளிப்படுத்துங்கள், கேளுங்கள், சேவைகளுடன் இணைக்க உதவ முன்வாருங்கள்.',
    tags: ['warning signs', 'mental health', 'training', 'recognition', 'early intervention'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },

  // === EXPLAINERS ===
  {
    id: 'wb-exp-1',
    titleEn: 'Cultural Healing Practices in Tamil Tradition',
    titleTa: 'தமிழ் பாரம்பரியத்தில் கலாச்சார குணமாக்கும் நடைமுறைகள்',
    bodyEn: 'Tamil communities have deep traditions of collective healing that existed long before modern psychology. Temple visits and prayer provide structure, community, and spiritual comfort. Kolam drawing each morning is a meditative practice that centres the mind. Singing — devotional songs, folk songs, lullabies — releases emotion and creates connection. Community cooking and sharing food nourishes both body and relationships. Elder guidance offers wisdom rooted in lived experience. These practices are not alternatives to professional help when it is needed, but they are powerful sources of daily strength and community resilience.',
    bodyTa: 'தமிழ் சமூகங்களுக்கு நவீன உளவியலுக்கு முன்பே நீண்டகாலமாக கூட்டு குணமாக்கும் பாரம்பரியங்கள் உள்ளன. கோயில் வருகைகள் மற்றும் வழிபாடு அமைப்பு, சமூகம், ஆன்மீக ஆறுதலை வழங்குகின்றன. ஒவ்வொரு காலையும் கோலம் போடுதல் மனதை மையப்படுத்தும் தியான நடைமுறை. பாடுதல் — பக்தி பாடல்கள், நாட்டுப்புற பாடல்கள், தாலாட்டு — உணர்வுகளை வெளியிடுகிறது, இணைப்பை உருவாக்குகிறது. சமூக சமையல் மற்றும் உணவு பகிர்வு உடலையும் உறவுகளையும் ஊட்டுகிறது. பெரியோர் வழிகாட்டுதல் வாழ்ந்த அனுபவத்தில் வேரூன்றிய ஞானத்தை வழங்குகிறது.',
    tags: ['cultural', 'spiritual', 'community', 'temple', 'kolam', 'traditional', 'resilience'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'wb-exp-2',
    titleEn: 'Understanding Post-Traumatic Stress',
    titleTa: 'அதிர்ச்சிக்குப் பிந்தைய மன அழுத்தத்தைப் புரிந்துகொள்ளுதல்',
    bodyEn: 'After experiencing war, displacement, violence, or loss, many people develop symptoms that are the body\'s natural response to abnormal events. These can include: flashbacks or nightmares about past events, feeling constantly on edge or easily startled, avoiding places or people that trigger memories, difficulty concentrating or sleeping, emotional numbness or sudden outbursts. These reactions are normal responses to abnormal situations — they do not mean you are weak or broken. With support, most people find that symptoms reduce over time. If symptoms persist for more than a month and affect your daily life, consider speaking with a counsellor.',
    bodyTa: 'போர், இடப்பெயர்வு, வன்முறை அல்லது இழப்பை அனுபவித்த பிறகு, பலர் அசாதாரண நிகழ்வுகளுக்கு உடலின் இயற்கையான பதிலான அறிகுறிகளை உருவாக்குகிறார்கள். இவற்றில் அடங்கும்: கடந்த நிகழ்வுகள் பற்றிய திடீர் நினைவுகள் அல்லது கனவுகள், தொடர்ந்து எச்சரிக்கையாக அல்லது எளிதில் திடுக்கிடும் உணர்வு, நினைவுகளை தூண்டும் இடங்கள் அல்லது நபர்களை தவிர்த்தல், கவனம் செலுத்துவதில் அல்லது தூங்குவதில் சிரமம். இந்த எதிர்வினைகள் அசாதாரண சூழ்நிலைகளுக்கான இயல்பான பதில்கள் — நீங்கள் பலவீனர் அல்ல.',
    tags: ['trauma', 'PTSD', 'mental health', 'awareness', 'war', 'displacement'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'wb-exp-3',
    titleEn: 'Wellbeing for Caregivers',
    titleTa: 'பராமரிப்பாளர்களுக்கான நல்வாழ்வு',
    bodyEn: 'If you care for a family member who is elderly, disabled, or unwell, your own wellbeing matters too. Caregiver burnout is real — signs include exhaustion, irritability, feeling trapped, neglecting your own health, and withdrawing from friends. Practical steps: ask for help from family members, take small breaks even if it is just 15 minutes, stay connected with at least one friend, eat regular meals, and do not feel guilty about needing rest. You are doing important work, and you deserve support too.',
    bodyTa: 'நீங்கள் வயதான, குறைபாடுள்ள அல்லது உடல்நிலை சரியில்லாத குடும்ப உறுப்பினரை பராமரிக்கிறீர்கள் என்றால், உங்கள் சொந்த நல்வாழ்வும் முக்கியமானது. பராமரிப்பாளர் சோர்வு உண்மையானது — அறிகுறிகளில் களைப்பு, எரிச்சல், சிக்கியிருப்பதாக உணர்வது, உங்கள் சொந்த ஆரோக்கியத்தை புறக்கணிப்பது, நண்பர்களிடமிருந்து விலகுவது ஆகியவை அடங்கும். நடைமுறை நடவடிக்கைகள்: குடும்ப உறுப்பினர்களிடம் உதவி கேளுங்கள், 15 நிமிடங்கள் என்றாலும் சிறிய இடைவெளிகள் எடுங்கள், குறைந்தது ஒரு நண்பருடன் தொடர்பில் இருங்கள்.',
    tags: ['caregivers', 'burnout', 'self-care', 'family', 'elderly care'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'wb-exp-4',
    titleEn: 'Helping Children Cope After Difficult Experiences',
    titleTa: 'கடினமான அனுபவங்களுக்குப் பிறகு குழந்தைகள் சமாளிக்க உதவுதல்',
    bodyEn: 'Children express distress differently from adults. Signs to watch for: bedwetting after being dry, clinging to parents, nightmares, aggression, withdrawal from play, or regression to younger behaviour. What helps: maintain daily routines, allow them to express feelings through play and drawing, answer their questions honestly in age-appropriate ways, provide physical comfort (hugs, staying close), reassure them that they are safe, and avoid exposing them to adult conversations about traumatic events. If concerning behaviour continues for more than a few weeks, seek support from a school counsellor or child psychologist.',
    bodyTa: 'குழந்தைகள் பெரியவர்களிலிருந்து வேறுபட்ட முறையில் துன்பத்தை வெளிப்படுத்துகிறார்கள். கவனிக்க வேண்டிய அறிகுறிகள்: உலர்ந்த பிறகு படுக்கையில் சிறுநீர் கழித்தல், பெற்றோரை பற்றிக்கொள்ளுதல், கனவுகள், ஆக்ரோஷம், விளையாட்டிலிருந்து விலகுதல், இளைய நடத்தைக்கு பின்வாங்குதல். என்ன உதவுகிறது: அன்றாட வழக்கங்களை பராமரியுங்கள், விளையாட்டு மற்றும் ஓவியம் மூலம் உணர்வுகளை வெளிப்படுத்த அனுமதியுங்கள், வயதுக்கு ஏற்ற முறையில் நேர்மையாக கேள்விகளுக்கு பதிலளியுங்கள்.',
    tags: ['children', 'trauma', 'parenting', 'coping', 'emotional support'],
    region: 'all',
    type: 'explainer',
  },
  {
    id: 'wb-exp-5',
    titleEn: 'Sleep and Wellbeing',
    titleTa: 'தூக்கமும் நல்வாழ்வும்',
    bodyEn: 'Poor sleep affects everything — mood, concentration, physical health, and relationships. If you are struggling to sleep: try to go to bed and wake up at the same time each day, avoid tea or coffee after 3pm, limit screen time before bed, keep your sleeping area cool and dark, try gentle breathing exercises (breathe in for 4 counts, hold for 4, breathe out for 6). If you are kept awake by worrying thoughts, try writing them down before bed — this helps your mind release them. Persistent sleeplessness (more than 3 weeks) may need medical attention.',
    bodyTa: 'மோசமான தூக்கம் எல்லாவற்றையும் பாதிக்கிறது — மனநிலை, கவனம், உடல் ஆரோக்கியம், உறவுகள். தூங்குவதில் சிரமம் இருந்தால்: ஒவ்வொரு நாளும் ஒரே நேரத்தில் படுக்கைக்கு சென்று எழுந்திருக்க முயற்சியுங்கள், மதியம் 3 மணிக்கு பிறகு தேநீர் அல்லது காபி தவிர்க்கவும், படுக்கைக்கு முன் திரை நேரத்தை குறையுங்கள், உங்கள் தூக்க பகுதியை குளிர்ச்சியாகவும் இருட்டாகவும் வையுங்கள், மென்மையான சுவாச பயிற்சிகளை முயற்சியுங்கள்.',
    tags: ['sleep', 'self-care', 'wellbeing', 'practical tips', 'health'],
    region: 'all',
    type: 'explainer',
  },
];
