import type { ContentItem } from '@/lib/types';

export const wellbeingContent: ContentItem[] = [
  {
    id: 'wb-1',
    titleEn: 'Shanthiham — Psychosocial Support',
    titleTa: 'சாந்தியம் — உளவியல் சமூக ஆதரவு',
    bodyEn: 'Shanthiham provides counselling, psychosocial support, and community-based mental health services across the Northern Province. They specialise in trauma recovery and offer services in Tamil.',
    bodyTa: 'சாந்தியம் வடக்கு மாகாணம் முழுவதும் ஆலோசனை, உளவியல் சமூக ஆதரவு மற்றும் சமூக அடிப்படையிலான மனநல சேவைகளை வழங்குகிறது. அவர்கள் அதிர்ச்சி மீட்சியில் நிபுணத்துவம் பெற்றவர்கள் மற்றும் தமிழில் சேவைகளை வழங்குகிறார்கள்.',
    tags: ['mental health', 'counselling', 'Northern Province'],
    region: 'north',
    contact: {
      phone: '+94 21 222 7865',
      email: 'info@shanthiham.org',
      website: 'https://shanthiham.org',
      address: 'Jaffna, Northern Province',
    },
    type: 'resource',
  },
  {
    id: 'wb-2',
    titleEn: 'National Institute of Mental Health',
    titleTa: 'தேசிய மனநல நிறுவனம்',
    bodyEn: 'The National Institute of Mental Health (NIMH) in Angoda provides inpatient and outpatient psychiatric services. Referrals from regional hospitals are accepted. Services are available in Sinhala, Tamil, and English.',
    bodyTa: 'அங்கொடையில் உள்ள தேசிய மனநல நிறுவனம் (NIMH) உள்நோயாளி மற்றும் வெளிநோயாளி மனநல சேவைகளை வழங்குகிறது. பிராந்திய மருத்துவமனைகளிலிருந்து பரிந்துரைகள் ஏற்றுக்கொள்ளப்படுகின்றன. சிங்களம், தமிழ், ஆங்கிலம் ஆகிய மொழிகளில் சேவைகள் கிடைக்கும்.',
    tags: ['mental health', 'hospital', 'national'],
    region: 'national',
    contact: {
      phone: '+94 11 257 8234',
      address: 'Angoda, Colombo',
    },
    type: 'resource',
  },
  {
    id: 'wb-3',
    titleEn: 'Peer Wellbeing Support Guide',
    titleTa: 'சக நல்வாழ்வு ஆதரவு வழிகாட்டி',
    bodyEn: 'A practical guide for community members on how to support someone who is experiencing emotional distress. Includes active listening techniques, what to say and what not to say, and when to refer to professional services.',
    bodyTa: 'உணர்வுப்பூர்வ மன உளைச்சலை அனுபவிக்கும் ஒருவரை எப்படி ஆதரிப்பது என்பது பற்றிய சமூக உறுப்பினர்களுக்கான நடைமுறை வழிகாட்டி. செயலில் கேட்கும் நுட்பங்கள், என்ன சொல்ல வேண்டும், என்ன சொல்லக்கூடாது, தொழில்முறை சேவைகளுக்கு எப்போது பரிந்துரைக்க வேண்டும் என்பதை உள்ளடக்கியது.',
    tags: ['peer support', 'training', 'guide'],
    region: 'all',
    type: 'guide',
    trainerResource: true,
  },
  {
    id: 'wb-4',
    titleEn: 'Sumithrayo — Crisis Support Line',
    titleTa: 'சுமித்ரயோ — நெருக்கடி ஆதரவு எண்',
    bodyEn: 'Sumithrayo offers a confidential crisis support telephone service for anyone who is distressed or suicidal. Available in Sinhala, Tamil, and English. The line operates 24 hours a day.',
    bodyTa: 'சுமித்ரயோ துன்பத்தில் உள்ள அல்லது தற்கொலை எண்ணம் கொண்ட எவருக்கும் ரகசியமான நெருக்கடி ஆதரவு தொலைபேசி சேவையை வழங்குகிறது. சிங்களம், தமிழ், ஆங்கிலம் ஆகிய மொழிகளில் கிடைக்கும். தினமும் 24 மணி நேரமும் இயங்குகிறது.',
    tags: ['crisis', 'hotline', '24/7'],
    region: 'national',
    contact: {
      phone: '+94 11 268 2535',
      website: 'https://sumithrayo.org',
    },
    type: 'resource',
  },
  {
    id: 'wb-5',
    titleEn: 'Cultural Healing Practices',
    titleTa: 'கலாச்சார குணமாக்கும் நடைமுறைகள்',
    bodyEn: 'An explainer on how Tamil cultural practices — temple worship, community gatherings, kolam drawing, traditional music, and elder mentorship — contribute to emotional and spiritual wellbeing. These are not replacements for professional care but are valuable sources of resilience.',
    bodyTa: 'தமிழ் கலாச்சார நடைமுறைகள் — கோயில் வழிபாடு, சமூக கூட்டங்கள், கோலம் போடுதல், பாரம்பரிய இசை, பெரியோர் வழிகாட்டுதல் — உணர்வு மற்றும் ஆன்மீக நல்வாழ்வுக்கு எவ்வாறு பங்களிக்கின்றன என்பது பற்றிய விளக்கம். இவை தொழில்முறை பராமரிப்புக்கு மாற்று அல்ல, ஆனால் நெகிழ்திறனின் மதிப்புமிக்க ஆதாரங்கள்.',
    tags: ['cultural', 'spiritual', 'community'],
    region: 'all',
    type: 'explainer',
  },
];
